import { getEvents, type Event } from '../../EventosYRetos/api/events';
import type { SocialPlatform } from '../../PlannerDeRedesSociales/api/social';
import type {
  EventChallengeContentKit,
  EventChallengeContentKitSet,
  GenerateContentKitRequest,
  GenerateContentKitResponse,
  ContentKitType,
  PlannerContentType,
} from '../types';

/**
 * Genera contenido automático para eventos/retos
 * User Story: Como Entrenador personal, Quiero que eventos/reto generen automáticamente kit de contenidos
 */
export const generateEventChallengeContentKit = async (
  request: GenerateContentKitRequest
): Promise<GenerateContentKitResponse> => {
  await new Promise(resolve => setTimeout(resolve, 600));

  // Obtener información del evento
  const events = await getEvents();
  const event = events.data.find(e => e.id === request.eventId);

  if (!event) {
    return {
      success: false,
      message: 'Evento no encontrado',
      kits: [],
    };
  }

  const kits: EventChallengeContentKit[] = [];
  const startDate = new Date(event.startDate);
  const endDate = new Date(event.endDate);

  // Generar contenido según el tipo de kit
  for (const kitType of request.kitTypes) {
    for (const platform of request.platforms) {
      const kit = generateKitContent(event, kitType, platform, request.scheduleConfig);
      kits.push(kit);
    }
  }

  return {
    success: true,
    message: `Se generaron ${kits.length} piezas de contenido para ${event.name}`,
    kits,
  };
};

/**
 * Genera el contenido de un kit específico
 */
function generateKitContent(
  event: Event,
  kitType: ContentKitType,
  platform: SocialPlatform,
  scheduleConfig?: GenerateContentKitRequest['scheduleConfig']
): EventChallengeContentKit {
  const startDate = new Date(event.startDate);
  const endDate = new Date(event.endDate);
  const now = new Date();

  let caption = '';
  let hashtags: string[] = [];
  let cta = '';
  let scheduledAt: string | undefined;
  let contentType: PlannerContentType = 'post';

  // Determinar formato según plataforma
  if (platform === 'instagram') {
    contentType = Math.random() > 0.5 ? 'reel' : 'post';
  } else if (platform === 'tiktok') {
    contentType = 'reel';
  }

  switch (kitType) {
    case 'invitacion':
      caption = generateInvitationContent(event);
      hashtags = generateInvitationHashtags(event);
      cta = '¡Reserva tu lugar ahora! 👇';
      
      // Programar días antes del evento
      const daysBefore = scheduleConfig?.invitacion?.daysBefore || 7;
      const invitationDate = new Date(startDate);
      invitationDate.setDate(invitationDate.getDate() - daysBefore);
      const invitationTime = scheduleConfig?.invitacion?.time || '10:00';
      const [hours, minutes] = invitationTime.split(':');
      invitationDate.setHours(parseInt(hours), parseInt(minutes), 0, 0);
      scheduledAt = invitationDate.toISOString();
      break;

    case 'recordatorio':
      caption = generateReminderContent(event);
      hashtags = generateReminderHashtags(event);
      cta = '¡No te lo pierdas! Últimas plazas disponibles 🚀';
      
      // Programar horas antes del evento
      const hoursBefore = scheduleConfig?.recordatorio?.hoursBefore || 24;
      const reminderDate = new Date(startDate);
      reminderDate.setHours(reminderDate.getHours() - hoursBefore);
      const reminderTime = scheduleConfig?.recordatorio?.time || '09:00';
      const [remHours, remMinutes] = reminderTime.split(':');
      reminderDate.setHours(parseInt(remHours), parseInt(remMinutes), 0, 0);
      scheduledAt = reminderDate.toISOString();
      break;

    case 'recap':
      caption = generateRecapContent(event);
      hashtags = generateRecapHashtags(event);
      cta = '¡Gracias a todos los participantes! 🙏';
      
      // Programar días después del evento
      const daysAfter = scheduleConfig?.recap?.daysAfter || 1;
      const recapDate = new Date(endDate);
      recapDate.setDate(recapDate.getDate() + daysAfter);
      const recapTime = scheduleConfig?.recap?.time || '18:00';
      const [recHours, recMinutes] = recapTime.split(':');
      recapDate.setHours(parseInt(recHours), parseInt(recMinutes), 0, 0);
      scheduledAt = recapDate.toISOString();
      break;
  }

  return {
    id: `kit_${event.id}_${kitType}_${platform}_${Date.now()}`,
    eventId: event.id,
    eventName: event.name,
    eventType: event.type,
    kitType,
    content: {
      caption,
      hashtags,
      cta,
      mediaSuggestions: [event.coverImageUrl || ''],
    },
    platform,
    contentType,
    scheduledAt,
    status: scheduledAt ? 'scheduled' : 'draft',
    autoGenerated: true,
    createdAt: new Date().toISOString(),
  };
}

function generateInvitationContent(event: Event): string {
  const startDate = new Date(event.startDate);
  const formattedDate = startDate.toLocaleDateString('es-ES', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  if (event.type === 'challenge') {
    return `🔥 ¡NUEVO RETO: ${event.name.toUpperCase()}! 🔥

📅 Inicio: ${formattedDate}
⏱️ Duración: ${calculateDuration(event)} días

${event.description}

✨ Lo que incluye:
${event.metrics?.map(m => `• ${m.name}`).join('\n') || '• Entrenamientos diarios\n• Seguimiento personalizado\n• Comunidad de apoyo'}

${event.fee > 0 ? `💰 Inversión: ${event.fee}${event.currency || '€'}` : '🎁 ¡GRATIS!'}
${event.maxParticipants ? `👥 Plazas limitadas: ${event.maxParticipants}` : ''}

¡Únete ahora y transforma tu vida! 💪`;
  } else {
    return `📅 ¡EVENTO PRÓXIMO: ${event.name}! 📅

📆 Fecha: ${formattedDate}
⏰ Hora: ${startDate.toLocaleTimeString('es-ES', { hour: '2-digit', minute: '2-digit' })}

${event.description}

${event.fee > 0 ? `💰 Precio: ${event.fee}${event.currency || '€'}` : '🎁 ¡GRATIS!'}
${event.maxParticipants ? `👥 Plazas limitadas: ${event.maxParticipants}` : ''}

¡Reserva tu lugar ahora! 👇`;
  }
}

function generateReminderContent(event: Event): string {
  const startDate = new Date(event.startDate);
  const hoursUntil = Math.floor((startDate.getTime() - Date.now()) / (1000 * 60 * 60));

  if (event.type === 'challenge') {
    return `⏰ RECORDATORIO: ${event.name} comienza ${hoursUntil <= 24 ? 'MAÑANA' : 'PRONTO'} ⏰

${hoursUntil <= 24 ? '¡Solo quedan unas horas!' : `Faltan ${Math.floor(hoursUntil / 24)} días`}

${event.description}

${event.participantCount > 0 ? `👥 Ya se han unido ${event.participantCount} personas` : '¡Sé el primero en unirte!'}
${event.maxParticipants ? `⚠️ Solo quedan ${event.maxParticipants - event.participantCount} plazas` : ''}

¡No te quedes fuera! Última oportunidad 🚀`;
  } else {
    return `⏰ RECORDATORIO: ${event.name} ${hoursUntil <= 24 ? 'MAÑANA' : 'PRONTO'} ⏰

📅 ${startDate.toLocaleDateString('es-ES', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })}
⏰ ${startDate.toLocaleTimeString('es-ES', { hour: '2-digit', minute: '2-digit' })}

${hoursUntil <= 24 ? '¡Solo quedan unas horas!' : `Faltan ${Math.floor(hoursUntil / 24)} días`}

${event.participantCount > 0 ? `👥 ${event.participantCount} personas ya confirmadas` : ''}
${event.maxParticipants ? `⚠️ Últimas ${event.maxParticipants - event.participantCount} plazas` : ''}

¡Nos vemos allí! 🎉`;
  }
}

function generateRecapContent(event: Event): string {
  const endDate = new Date(event.endDate);
  const duration = calculateDuration(event);

  if (event.type === 'challenge') {
    return `🎉 ¡RETO COMPLETADO: ${event.name}! 🎉

${duration} días increíbles han llegado a su fin.

📊 Resultados:
${event.participantCount > 0 ? `👥 ${event.participantCount} participantes` : ''}
${event.stats?.completionRate ? `✅ ${Math.round(event.stats.completionRate * 100)}% de finalización` : ''}
${event.stats?.averageEngagement ? `⭐ ${event.stats.averageEngagement.toFixed(1)}/5 de engagement promedio` : ''}

${event.stats?.totalRevenue ? `💰 Recaudación total: ${event.stats.totalRevenue.toFixed(2)}${event.currency || '€'}` : ''}

¡Gracias a todos los que participaron! Vuestro esfuerzo y dedicación han sido increíbles 🙏

¿Quieres ver los resultados completos? 👇`;
  } else {
    return `🎉 ¡EVENTO FINALIZADO: ${event.name}! 🎉

¡Qué experiencia tan increíble! Gracias a todos los participantes.

📊 Resumen:
${event.participantCount > 0 ? `👥 ${event.participantCount} asistentes` : ''}
${event.stats?.averageEngagement ? `⭐ ${event.stats.averageEngagement.toFixed(1)}/5 de satisfacción` : ''}

¡Fue un placer compartir este momento con vosotros! 🙏

¿Quieres ver las fotos y momentos destacados? 👇`;
  }
}

function generateInvitationHashtags(event: Event): string[] {
  const baseHashtags = ['fitness', 'entrenamiento', 'salud'];
  
  if (event.type === 'challenge') {
    return [...baseHashtags, 'reto', 'challenge', 'transformacion', 'motivacion', 'fitnessmotivation'];
  } else if (event.type === 'bootcamp') {
    return [...baseHashtags, 'bootcamp', 'entrenamientofuncional', 'grupo'];
  } else if (event.type === 'workshop') {
    return [...baseHashtags, 'workshop', 'aprendizaje', 'educacion'];
  }
  
  return baseHashtags;
}

function generateReminderHashtags(event: Event): string[] {
  return generateInvitationHashtags(event).concat(['ultimallamada', 'nopierdas', 'oportunidad']);
}

function generateRecapHashtags(event: Event): string[] {
  return generateInvitationHashtags(event).concat(['resultados', 'exito', 'completado', 'gracias']);
}

function calculateDuration(event: Event): number {
  const start = new Date(event.startDate);
  const end = new Date(event.endDate);
  const diffTime = Math.abs(end.getTime() - start.getTime());
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  return diffDays || 1;
}

/**
 * Obtiene todos los kits de contenido generados para eventos/retos
 */
export const getEventChallengeContentKits = async (): Promise<EventChallengeContentKitSet[]> => {
  await new Promise(resolve => setTimeout(resolve, 400));

  const events = await getEvents({ status: 'upcoming' });
  const activeEvents = await getEvents({ status: 'active' });
  const allEvents = [...events.data, ...activeEvents.data];

  // Simular kits generados para algunos eventos
  const kits: EventChallengeContentKitSet[] = allEvents.slice(0, 3).map(event => {
    const startDate = new Date(event.startDate);
    const invitationDate = new Date(startDate);
    invitationDate.setDate(invitationDate.getDate() - 7);
    invitationDate.setHours(10, 0, 0, 0);

    const reminderDate = new Date(startDate);
    reminderDate.setHours(reminderDate.getHours() - 24);
    reminderDate.setHours(9, 0, 0, 0);

    const endDate = new Date(event.endDate);
    const recapDate = new Date(endDate);
    recapDate.setDate(recapDate.getDate() + 1);
    recapDate.setHours(18, 0, 0, 0);

    return {
      eventId: event.id,
      eventName: event.name,
      eventType: event.type,
      startDate: event.startDate,
      endDate: event.endDate,
      kits: {
        invitacion: {
          id: `kit_${event.id}_invitacion_insta`,
          eventId: event.id,
          eventName: event.name,
          eventType: event.type,
          kitType: 'invitacion',
          content: {
            caption: generateInvitationContent(event),
            hashtags: generateInvitationHashtags(event),
            cta: '¡Reserva tu lugar ahora! 👇',
            mediaSuggestions: [event.coverImageUrl || ''],
          },
          platform: 'instagram',
          contentType: 'post',
          scheduledAt: invitationDate.toISOString(),
          status: 'scheduled',
          autoGenerated: true,
          createdAt: new Date().toISOString(),
        },
        recordatorio: {
          id: `kit_${event.id}_recordatorio_insta`,
          eventId: event.id,
          eventName: event.name,
          eventType: event.type,
          kitType: 'recordatorio',
          content: {
            caption: generateReminderContent(event),
            hashtags: generateReminderHashtags(event),
            cta: '¡No te lo pierdas! Últimas plazas disponibles 🚀',
            mediaSuggestions: [event.coverImageUrl || ''],
          },
          platform: 'instagram',
          contentType: 'post',
          scheduledAt: reminderDate.toISOString(),
          status: 'scheduled',
          autoGenerated: true,
          createdAt: new Date().toISOString(),
        },
        recap: {
          id: `kit_${event.id}_recap_insta`,
          eventId: event.id,
          eventName: event.name,
          eventType: event.type,
          kitType: 'recap',
          content: {
            caption: generateRecapContent(event),
            hashtags: generateRecapHashtags(event),
            cta: '¡Gracias a todos los participantes! 🙏',
            mediaSuggestions: [event.coverImageUrl || ''],
          },
          platform: 'instagram',
          contentType: 'post',
          scheduledAt: recapDate.toISOString(),
          status: 'draft',
          autoGenerated: true,
          createdAt: new Date().toISOString(),
        },
      },
      autoGenerationEnabled: true,
      createdAt: new Date().toISOString(),
    };
  });

  return kits;
};

