export {
  fetchAcquisitionAISuggestions,
  fetchAcquisitionCampaigns,
  fetchAcquisitionEvents,
  fetchAcquisitionTopFunnels,
  fetchFunnelsAcquisitionKPIs,
  fetchWorkspaceBlueprints,
  fetchLeadRiskAlerts,
  fetchFirstSessionConversionMetric,
  fetchSocialMediaMetrics,
  fetchReferralProgramMetrics,
  fetchRecommendedFunnels,
  saveBuyerPersonas,
  savePainPoints,
  adaptFunnelCopy,
  getFunnelPersonalization,
  getFavoriteToneConfigs,
  saveFavoriteToneConfig,
  deleteFavoriteToneConfig,
  getFavoriteCTAConfigs,
  saveFavoriteCTAConfig,
  deleteFavoriteCTAConfig,
  getToneAndCTAPresets,
  saveToneAndCTAPreset,
  getLeadMagnetFormatSuggestions,
  generateLandingPageCopy,
  suggestIntelligentForm,
  saveIntelligentForm,
  getIntelligentForms,
  submitIntelligentForm,
  getFunnelExperiments,
  getFunnelExperiment,
  createFunnelExperiment,
  updateFunnelExperimentStatus,
  generateAIExperimentSuggestions,
  getFunnelPerformanceAnalysis,
  getFunnelBottlenecks,
  getNurturingRecommendations,
  analyzeLeadMagnetResponses,
  exportFunnelToCampaigns,
  convertFunnelToChallenge,
  getTopReels,
  getTopTestimonials,
  getFunnelContentRecommendations,
  connectContentToFunnel,
  getFunnelConnectedContent,
  disconnectContentFromFunnel,
  fetchProjectedRevenueByFunnel,
  fetchFunnelLeadGenerationAlerts,
  getFunnelQualitativeNotes,
  createFunnelQualitativeNote,
  updateFunnelQualitativeNote,
  getProposalLearning,
  trackProposal,
  getProposalSimilarityMatches,
  getCommunityInsights,
  getFunnelCommunityInsightsStatus,
  updateFunnelWithCommunityInsights,
  getFunnelCommunityInsightsRecommendations,
  generateFollowUpTemplates,
  applyFollowUpTemplate,
  getFollowUpTemplates,
  getFunnelCalendar,
  generateFunnelAISummary,
  shareFunnelAISummary,
  getFunnelAISummaries,
  getFunnelRetrospective,
  createFunnelRetrospective,
  updateFunnelRetrospective,
} from './funnelsAdquisicion';










