import {
  CommunityActivityCorrelationReport,
  CommunityActivityType,
  ActivityStatus,
  CommunityFidelizacionSnapshot,
  CustomerSegmentType,
} from '../types';

const MOCK_ACTIVITIES = [
  {
    id: 'act_001',
    name: 'Reto de 21 días de Transformación',
    type: 'reto' as CommunityActivityType,
    description: 'Reto comunitario de 21 días para transformación física y mental',
    startDate: '2025-09-15T00:00:00Z',
    endDate: '2025-10-05T23:59:59Z',
    status: 'completado' as ActivityStatus,
    investment: 2500,
    participants: 45,
    targetAudience: ['embajador', 'regular'] as CustomerSegmentType[],
    organizer: 'Marina (CX Lead)',
    tags: ['transformación', 'comunidad', 'reto'],
  },
  {
    id: 'act_002',
    name: 'Workshop de Nutrición Deportiva',
    type: 'workshop' as CommunityActivityType,
    description: 'Taller presencial sobre nutrición deportiva y suplementación',
    startDate: '2025-09-20T10:00:00Z',
    endDate: '2025-09-20T14:00:00Z',
    status: 'completado' as ActivityStatus,
    investment: 800,
    participants: 28,
    targetAudience: ['vip', 'regular'] as CustomerSegmentType[],
    organizer: 'Luis (Marketing)',
    tags: ['nutrición', 'educación', 'workshop'],
  },
  {
    id: 'act_003',
    name: 'Competencia de Fuerza',
    type: 'competencia' as CommunityActivityType,
    description: 'Competencia interna de levantamiento de pesas y fuerza',
    startDate: '2025-09-25T08:00:00Z',
    endDate: '2025-09-25T18:00:00Z',
    status: 'completado' as ActivityStatus,
    investment: 1200,
    participants: 32,
    targetAudience: ['embajador', 'vip', 'regular'] as CustomerSegmentType[],
    organizer: 'Adriana (Research)',
    tags: ['competencia', 'fuerza', 'comunidad'],
  },
  {
    id: 'act_004',
    name: 'Evento de Networking Fitness',
    type: 'networking' as CommunityActivityType,
    description: 'Evento de networking para conectar miembros de la comunidad',
    startDate: '2025-09-28T18:00:00Z',
    endDate: '2025-09-28T22:00:00Z',
    status: 'completado' as ActivityStatus,
    investment: 600,
    participants: 22,
    targetAudience: ['embajador', 'vip'] as CustomerSegmentType[],
    organizer: 'Marina (CX Lead)',
    tags: ['networking', 'comunidad', 'social'],
  },
  {
    id: 'act_005',
    name: 'Webinar de Bienestar Mental',
    type: 'webinar' as CommunityActivityType,
    description: 'Webinar sobre bienestar mental y manejo del estrés',
    startDate: '2025-10-01T19:00:00Z',
    endDate: '2025-10-01T20:30:00Z',
    status: 'completado' as ActivityStatus,
    investment: 400,
    participants: 65,
    targetAudience: ['regular', 'nuevo'] as CustomerSegmentType[],
    organizer: 'Luis (Marketing)',
    tags: ['bienestar', 'mental', 'webinar'],
  },
  {
    id: 'act_006',
    name: 'Celebración de Logros Mensual',
    type: 'celebracion' as CommunityActivityType,
    description: 'Evento de celebración de logros y reconocimientos mensuales',
    startDate: '2025-10-05T18:00:00Z',
    endDate: '2025-10-05T21:00:00Z',
    status: 'completado' as ActivityStatus,
    investment: 900,
    participants: 38,
    targetAudience: ['embajador', 'vip', 'regular'] as CustomerSegmentType[],
    organizer: 'Adriana (Research)',
    tags: ['celebración', 'reconocimiento', 'comunidad'],
  },
  {
    id: 'act_007',
    name: 'Programa de Mentoría',
    type: 'programa' as CommunityActivityType,
    description: 'Programa de mentoría donde miembros experimentados guían a nuevos miembros',
    startDate: '2025-09-10T00:00:00Z',
    endDate: '2025-12-10T23:59:59Z',
    status: 'activo' as ActivityStatus,
    investment: 1800,
    participants: 24,
    targetAudience: ['embajador', 'vip'] as CustomerSegmentType[],
    organizer: 'Marina (CX Lead)',
    tags: ['mentoría', 'programa', 'comunidad'],
  },
];

const MOCK_CORRELATION_REPORT: CommunityActivityCorrelationReport = {
  id: 'corr_001',
  period: '30d',
  generatedAt: new Date().toISOString(),
  correlations: [
    {
      activity: MOCK_ACTIVITIES[0],
      retentionImpact: {
        activityId: 'act_001',
        activityName: 'Reto de 21 días de Transformación',
        retentionRate: 88.9,
        retentionLift: 12.5,
        participantsRetained: 40,
        totalParticipants: 45,
        retentionPeriod: '90d',
        baselineRetention: 76.4,
        retentionChange: 12.5,
        retentionTrend: 'up',
      },
      revenueImpact: {
        activityId: 'act_001',
        activityName: 'Reto de 21 días de Transformación',
        revenueGenerated: 12500,
        revenueAttributed: 18000,
        revenueLift: 25.3,
        averageRevenuePerParticipant: 450,
        roi: 620,
        roiPeriod: '90d',
        paybackPeriod: 45,
        baselineRevenue: 14375,
        revenueChange: 3625,
        revenueTrend: 'up',
      },
      overallImpact: 85,
      impactScore: 92,
      investmentJustification: {
        roi: 620,
        retentionValue: 8750,
        revenueValue: 18000,
        totalValue: 26750,
        paybackPeriod: 45,
        recommendation: 'increase',
        reasoning:
          'El reto de 21 días muestra un ROI excepcional del 620% y un incremento en retención del 12.5%. Se recomienda aumentar la inversión y frecuencia de este tipo de retos.',
      },
      comparison: {
        rank: 1,
        percentile: 95,
        betterThanAverage: true,
      },
    },
    {
      activity: MOCK_ACTIVITIES[1],
      retentionImpact: {
        activityId: 'act_002',
        activityName: 'Workshop de Nutrición Deportiva',
        retentionRate: 82.1,
        retentionLift: 8.3,
        participantsRetained: 23,
        totalParticipants: 28,
        retentionPeriod: '90d',
        baselineRetention: 73.8,
        retentionChange: 8.3,
        retentionTrend: 'up',
      },
      revenueImpact: {
        activityId: 'act_002',
        activityName: 'Workshop de Nutrición Deportiva',
        revenueGenerated: 8400,
        revenueAttributed: 11200,
        revenueLift: 15.2,
        averageRevenuePerParticipant: 400,
        roi: 1300,
        roiPeriod: '90d',
        paybackPeriod: 21,
        baselineRevenue: 9716,
        revenueChange: 1484,
        revenueTrend: 'up',
      },
      overallImpact: 72,
      impactScore: 78,
      investmentJustification: {
        roi: 1300,
        retentionValue: 4200,
        revenueValue: 11200,
        totalValue: 15400,
        paybackPeriod: 21,
        recommendation: 'maintain',
        reasoning:
          'El workshop muestra un ROI excelente del 1300% y buena retención. Se recomienda mantener la inversión actual y considerar aumentar la frecuencia.',
      },
      comparison: {
        rank: 2,
        percentile: 85,
        betterThanAverage: true,
      },
    },
    {
      activity: MOCK_ACTIVITIES[2],
      retentionImpact: {
        activityId: 'act_003',
        activityName: 'Competencia de Fuerza',
        retentionRate: 75.0,
        retentionLift: 5.2,
        participantsRetained: 24,
        totalParticipants: 32,
        retentionPeriod: '90d',
        baselineRetention: 69.8,
        retentionChange: 5.2,
        retentionTrend: 'up',
      },
      revenueImpact: {
        activityId: 'act_003',
        activityName: 'Competencia de Fuerza',
        revenueGenerated: 9600,
        revenueAttributed: 12800,
        revenueLift: 12.8,
        averageRevenuePerParticipant: 400,
        roi: 967,
        roiPeriod: '90d',
        paybackPeriod: 28,
        baselineRevenue: 11341,
        revenueChange: 1459,
        revenueTrend: 'up',
      },
      overallImpact: 65,
      impactScore: 70,
      investmentJustification: {
        roi: 967,
        retentionValue: 3500,
        revenueValue: 12800,
        totalValue: 16300,
        paybackPeriod: 28,
        recommendation: 'maintain',
        reasoning:
          'La competencia muestra un ROI sólido del 967% y buena participación. Se recomienda mantener la inversión y mejorar la experiencia para aumentar la retención.',
      },
      comparison: {
        rank: 3,
        percentile: 70,
        betterThanAverage: true,
      },
    },
    {
      activity: MOCK_ACTIVITIES[3],
      retentionImpact: {
        activityId: 'act_004',
        activityName: 'Evento de Networking Fitness',
        retentionRate: 68.2,
        retentionLift: 3.1,
        participantsRetained: 15,
        totalParticipants: 22,
        retentionPeriod: '90d',
        baselineRetention: 65.1,
        retentionChange: 3.1,
        retentionTrend: 'steady',
      },
      revenueImpact: {
        activityId: 'act_004',
        activityName: 'Evento de Networking Fitness',
        revenueGenerated: 4400,
        revenueAttributed: 6600,
        revenueLift: 8.5,
        averageRevenuePerParticipant: 300,
        roi: 1000,
        roiPeriod: '90d',
        paybackPeriod: 27,
        baselineRevenue: 6083,
        revenueChange: 517,
        revenueTrend: 'steady',
      },
      overallImpact: 55,
      impactScore: 60,
      investmentJustification: {
        roi: 1000,
        retentionValue: 2200,
        revenueValue: 6600,
        totalValue: 8800,
        paybackPeriod: 27,
        recommendation: 'maintain',
        reasoning:
          'El evento de networking muestra un ROI bueno del 1000% pero menor impacto en retención. Se recomienda mantener la inversión y mejorar la experiencia para aumentar el engagement.',
      },
      comparison: {
        rank: 4,
        percentile: 55,
        betterThanAverage: false,
      },
    },
    {
      activity: MOCK_ACTIVITIES[4],
      retentionImpact: {
        activityId: 'act_005',
        activityName: 'Webinar de Bienestar Mental',
        retentionRate: 72.3,
        retentionLift: 4.5,
        participantsRetained: 47,
        totalParticipants: 65,
        retentionPeriod: '90d',
        baselineRetention: 67.8,
        retentionChange: 4.5,
        retentionTrend: 'up',
      },
      revenueImpact: {
        activityId: 'act_005',
        activityName: 'Webinar de Bienestar Mental',
        revenueGenerated: 7800,
        revenueAttributed: 10400,
        revenueLift: 10.2,
        averageRevenuePerParticipant: 160,
        roi: 2500,
        roiPeriod: '90d',
        paybackPeriod: 12,
        baselineRevenue: 9436,
        revenueChange: 964,
        revenueTrend: 'up',
      },
      overallImpact: 68,
      impactScore: 73,
      investmentJustification: {
        roi: 2500,
        retentionValue: 3900,
        revenueValue: 10400,
        totalValue: 14300,
        paybackPeriod: 12,
        recommendation: 'increase',
        reasoning:
          'El webinar muestra un ROI excepcional del 2500% con bajo coste y alta participación. Se recomienda aumentar la inversión y frecuencia de webinars educativos.',
      },
      comparison: {
        rank: 2,
        percentile: 88,
        betterThanAverage: true,
      },
    },
    {
      activity: MOCK_ACTIVITIES[5],
      retentionImpact: {
        activityId: 'act_006',
        activityName: 'Celebración de Logros Mensual',
        retentionRate: 78.9,
        retentionLift: 6.8,
        participantsRetained: 30,
        totalParticipants: 38,
        retentionPeriod: '90d',
        baselineRetention: 72.1,
        retentionChange: 6.8,
        retentionTrend: 'up',
      },
      revenueImpact: {
        activityId: 'act_006',
        activityName: 'Celebración de Logros Mensual',
        revenueGenerated: 7600,
        revenueAttributed: 9500,
        revenueLift: 11.5,
        averageRevenuePerParticipant: 250,
        roi: 956,
        roiPeriod: '90d',
        paybackPeriod: 29,
        baselineRevenue: 8519,
        revenueChange: 981,
        revenueTrend: 'up',
      },
      overallImpact: 70,
      impactScore: 75,
      investmentJustification: {
        roi: 956,
        retentionValue: 3800,
        revenueValue: 9500,
        totalValue: 13300,
        paybackPeriod: 29,
        recommendation: 'maintain',
        reasoning:
          'La celebración muestra un ROI sólido del 956% y buena retención. Se recomienda mantener la inversión y continuar con la frecuencia mensual.',
      },
      comparison: {
        rank: 3,
        percentile: 72,
        betterThanAverage: true,
      },
    },
    {
      activity: MOCK_ACTIVITIES[6],
      retentionImpact: {
        activityId: 'act_007',
        activityName: 'Programa de Mentoría',
        retentionRate: 91.7,
        retentionLift: 15.2,
        participantsRetained: 22,
        totalParticipants: 24,
        retentionPeriod: '90d',
        baselineRetention: 76.5,
        retentionChange: 15.2,
        retentionTrend: 'up',
      },
      revenueImpact: {
        activityId: 'act_007',
        activityName: 'Programa de Mentoría',
        revenueGenerated: 10800,
        revenueAttributed: 14400,
        revenueLift: 20.5,
        averageRevenuePerParticipant: 600,
        roi: 700,
        roiPeriod: '90d',
        paybackPeriod: 51,
        baselineRevenue: 11952,
        revenueChange: 2448,
        revenueTrend: 'up',
      },
      overallImpact: 88,
      impactScore: 90,
      investmentJustification: {
        roi: 700,
        retentionValue: 7200,
        revenueValue: 14400,
        totalValue: 21600,
        paybackPeriod: 51,
        recommendation: 'increase',
        reasoning:
          'El programa de mentoría muestra un ROI excelente del 700% y el mayor incremento en retención (15.2%). Se recomienda aumentar la inversión y expandir el programa a más miembros.',
      },
      comparison: {
        rank: 1,
        percentile: 92,
        betterThanAverage: true,
      },
    },
  ],
  summary: {
    totalActivities: 7,
    totalInvestment: 8200,
    totalRevenueGenerated: 61100,
    totalRetentionLift: 55.6,
    averageROI: 1286,
    topPerformer: null,
    worstPerformer: null,
  },
  aiInsights: {
    keyFindings: [
      'Las actividades de comunidad generan un ROI promedio del 1286% y un incremento en retención del 7.9%',
      'Los retos de transformación y programas de mentoría muestran el mayor impacto en retención (12.5% y 15.2%)',
      'Los webinars educativos tienen el mejor ROI (2500%) con el menor coste de inversión',
      'Las actividades que involucran múltiples segmentos tienen mayor impacto en retención',
    ],
    recommendations: [
      'Aumentar la inversión en retos de transformación y programas de mentoría debido a su alto impacto en retención',
      'Incrementar la frecuencia de webinars educativos debido a su excelente ROI y bajo coste',
      'Mejorar la experiencia de eventos de networking para aumentar el engagement y retención',
      'Expandir programas exitosos a más segmentos de clientes para maximizar el impacto',
    ],
    opportunities: [
      'Crear nuevos retos de transformación trimestrales para mantener el engagement',
      'Desarrollar programas de mentoría para segmentos específicos (VIP, Embajadores)',
      'Aumentar la frecuencia de webinars educativos a semanal para maximizar el ROI',
      'Crear eventos de celebración trimestrales además de los mensuales',
    ],
    risks: [
      'El alto coste de retos de transformación podría reducir el ROI si no se mantiene la participación',
      'La saturación de eventos podría reducir el engagement y la asistencia',
      'La falta de seguimiento después de eventos podría reducir el impacto en retención',
    ],
    investmentRecommendations: [
      {
        activityId: 'act_001',
        activityName: 'Reto de 21 días de Transformación',
        recommendation: 'increase',
        reasoning:
          'El reto muestra un ROI excepcional del 620% y un incremento en retención del 12.5%. Se recomienda aumentar la inversión de €2,500 a €3,500 para aumentar la participación y el impacto.',
        suggestedInvestment: 3500,
      },
      {
        activityId: 'act_007',
        activityName: 'Programa de Mentoría',
        recommendation: 'increase',
        reasoning:
          'El programa muestra el mayor impacto en retención (15.2%) y un ROI excelente del 700%. Se recomienda aumentar la inversión de €1,800 a €2,500 para expandir el programa a más miembros.',
        suggestedInvestment: 2500,
      },
      {
        activityId: 'act_005',
        activityName: 'Webinar de Bienestar Mental',
        recommendation: 'increase',
        reasoning:
          'El webinar muestra el mejor ROI (2500%) con el menor coste. Se recomienda aumentar la inversión de €400 a €600 para mejorar la calidad y aumentar la frecuencia.',
        suggestedInvestment: 600,
      },
      {
        activityId: 'act_004',
        activityName: 'Evento de Networking Fitness',
        recommendation: 'maintain',
        reasoning:
          'El evento muestra un ROI bueno del 1000% pero menor impacto en retención. Se recomienda mantener la inversión actual y mejorar la experiencia para aumentar el engagement.',
      },
    ],
  },
  trends: [
    {
      activityType: 'reto',
      averageROI: 620,
      averageRetentionLift: 12.5,
      trendDirection: 'up',
    },
    {
      activityType: 'workshop',
      averageROI: 1300,
      averageRetentionLift: 8.3,
      trendDirection: 'up',
    },
    {
      activityType: 'competencia',
      averageROI: 967,
      averageRetentionLift: 5.2,
      trendDirection: 'steady',
    },
    {
      activityType: 'networking',
      averageROI: 1000,
      averageRetentionLift: 3.1,
      trendDirection: 'steady',
    },
    {
      activityType: 'webinar',
      averageROI: 2500,
      averageRetentionLift: 4.5,
      trendDirection: 'up',
    },
    {
      activityType: 'celebracion',
      averageROI: 956,
      averageRetentionLift: 6.8,
      trendDirection: 'up',
    },
    {
      activityType: 'programa',
      averageROI: 700,
      averageRetentionLift: 15.2,
      trendDirection: 'up',
    },
  ],
};

// Calcular topPerformer y worstPerformer
MOCK_CORRELATION_REPORT.summary.topPerformer = MOCK_CORRELATION_REPORT.correlations[0];
MOCK_CORRELATION_REPORT.summary.worstPerformer = MOCK_CORRELATION_REPORT.correlations[3];

export const CommunityActivityCorrelationAPI = {
  async getActivityCorrelationReport(
    period: CommunityFidelizacionSnapshot['period'] = '30d',
  ): Promise<CommunityActivityCorrelationReport> {
    // Simular delay de API
    await new Promise((resolve) => setTimeout(resolve, 500));

    return {
      ...MOCK_CORRELATION_REPORT,
      period,
      generatedAt: new Date().toISOString(),
    };
  },

  async generateActivityCorrelationReport(
    period: CommunityFidelizacionSnapshot['period'],
  ): Promise<CommunityActivityCorrelationReport> {
    // Simular generación de reporte con IA
    await new Promise((resolve) => setTimeout(resolve, 1500));

    return {
      ...MOCK_CORRELATION_REPORT,
      period,
      generatedAt: new Date().toISOString(),
    };
  },

  async getActivityCorrelation(activityId: string) {
    const report = await this.getActivityCorrelationReport('30d');
    return report.correlations.find((c) => c.activity.id === activityId);
  },
};
