import { Reserva, Clase } from '../types';

export const getReservas = async (fechaInicio: Date, fechaFin: Date, role: 'entrenador' | 'gimnasio'): Promise<Reserva[]> => {
  await new Promise(resolve => setTimeout(resolve, 300));
  
  const hoy = new Date();
  const addDays = (days: number) => new Date(hoy.getTime() + days * 86400000);
  
  if (role === 'entrenador') {
    return [
      {
        id: '1',
        clienteId: 'cliente1',
        clienteNombre: 'Juan Pérez',
        fecha: addDays(1),
        horaInicio: '10:00',
        horaFin: '11:00',
        tipo: 'sesion-1-1',
        tipoSesion: 'presencial',
        estado: 'confirmada',
        precio: 50,
        pagado: true,
        createdAt: addDays(-5),
        updatedAt: addDays(-2),
      },
      {
        id: '2',
        clienteId: 'cliente2',
        clienteNombre: 'María García',
        fecha: addDays(2),
        horaInicio: '12:00',
        horaFin: '12:45',
        tipo: 'sesion-1-1',
        tipoSesion: 'videollamada',
        estado: 'confirmada',
        precio: 45,
        pagado: true,
        createdAt: addDays(-4),
        updatedAt: addDays(-1),
      },
      {
        id: '3',
        clienteId: 'cliente3',
        clienteNombre: 'Carlos Ruiz',
        fecha: addDays(3),
        horaInicio: '09:00',
        horaFin: '10:00',
        tipo: 'sesion-1-1',
        tipoSesion: 'presencial',
        estado: 'confirmada',
        precio: 50,
        pagado: false,
        createdAt: addDays(-6),
        updatedAt: addDays(-3),
      },
      {
        id: '4',
        clienteId: 'cliente4',
        clienteNombre: 'Ana Martínez',
        fecha: addDays(4),
        horaInicio: '16:00',
        horaFin: '17:00',
        tipo: 'sesion-1-1',
        tipoSesion: 'presencial',
        estado: 'pendiente',
        precio: 50,
        pagado: false,
        createdAt: addDays(-3),
        updatedAt: addDays(-3),
      },
      {
        id: '5',
        clienteId: 'cliente5',
        clienteNombre: 'Luis García',
        fecha: addDays(2),
        horaInicio: '11:00',
        horaFin: '11:30',
        tipo: 'sesion-1-1',
        tipoSesion: 'videollamada',
        estado: 'cancelada',
        precio: 45,
        pagado: false,
        observaciones: 'Cliente canceló por motivo personal',
        createdAt: addDays(-8),
        updatedAt: addDays(-1),
      },
    ];
  }
  
  // Para gimnasio - clases grupales
  return [
    {
      id: '6',
      clienteId: 'cliente6',
      clienteNombre: 'Ana López',
      fecha: hoy,
      horaInicio: '10:00',
      horaFin: '11:00',
      tipo: 'clase-grupal',
      claseId: 'clase1',
      claseNombre: 'Spinning',
      estado: 'confirmada',
      precio: 15,
      pagado: true,
      capacidad: 20,
      ocupacion: 18,
      createdAt: addDays(-3),
      updatedAt: addDays(-1),
    },
    {
      id: '7',
      clienteId: 'cliente7',
      clienteNombre: 'Diego Fernández',
      fecha: hoy,
      horaInicio: '12:00',
      horaFin: '13:00',
      tipo: 'boxeo',
      claseId: 'clase2',
      claseNombre: 'Boxeo',
      estado: 'confirmada',
      precio: 20,
      pagado: true,
      capacidad: 15,
      ocupacion: 12,
      createdAt: addDays(-2),
      updatedAt: addDays(-1),
    },
    {
      id: '8',
      clienteId: 'cliente8',
      clienteNombre: 'Elena Sánchez',
      fecha: addDays(1),
      horaInicio: '08:00',
      horaFin: '09:00',
      tipo: 'clase-grupal',
      claseId: 'clase3',
      claseNombre: 'Spinning',
      estado: 'confirmada',
      precio: 15,
      pagado: true,
      capacidad: 30,
      ocupacion: 28,
      createdAt: addDays(-4),
      updatedAt: addDays(-2),
    },
    {
      id: '9',
      clienteId: 'cliente9',
      clienteNombre: 'Roberto Martín',
      fecha: addDays(1),
      horaInicio: '18:30',
      horaFin: '19:30',
      tipo: 'clase-grupal',
      claseId: 'clase4',
      claseNombre: 'Pilates',
      estado: 'pendiente',
      precio: 18,
      pagado: false,
      capacidad: 15,
      ocupacion: 12,
      createdAt: addDays(-2),
      updatedAt: addDays(-2),
    },
    {
      id: '10',
      clienteId: 'cliente10',
      clienteNombre: 'Laura Torres',
      fecha: addDays(2),
      horaInicio: '19:00',
      horaFin: '20:00',
      tipo: 'hiit',
      claseId: 'clase5',
      claseNombre: 'HIIT',
      estado: 'confirmada',
      precio: 20,
      pagado: true,
      capacidad: 20,
      ocupacion: 18,
      createdAt: addDays(-5),
      updatedAt: addDays(-3),
    },
    {
      id: '11',
      clienteId: 'cliente11',
      clienteNombre: 'Miguel Vargas',
      fecha: addDays(3),
      horaInicio: '09:00',
      horaFin: '10:00',
      tipo: 'clase-grupal',
      claseId: 'clase6',
      claseNombre: 'Stretching',
      estado: 'cancelada',
      precio: 15,
      pagado: false,
      capacidad: 18,
      ocupacion: 14,
      observaciones: 'Cancelación por baja demanda',
      createdAt: addDays(-7),
      updatedAt: addDays(-1),
    },
    {
      id: '12',
      clienteId: 'cliente12',
      clienteNombre: 'Patricia Jiménez',
      fecha: addDays(3),
      horaInicio: '11:00',
      horaFin: '12:00',
      tipo: 'fisio',
      claseId: 'clase7',
      claseNombre: 'Fisioterapia',
      estado: 'confirmada',
      precio: 40,
      pagado: true,
      capacidad: 1,
      ocupacion: 1,
      createdAt: addDays(-4),
      updatedAt: addDays(-2),
    },
    {
      id: '13',
      clienteId: 'cliente13',
      clienteNombre: 'Javier Ramos',
      fecha: addDays(4),
      horaInicio: '14:00',
      horaFin: '15:00',
      tipo: 'nutricion',
      claseId: 'clase8',
      claseNombre: 'Consulta Nutricional',
      estado: 'confirmada',
      precio: 50,
      pagado: true,
      capacidad: 1,
      ocupacion: 1,
      createdAt: addDays(-3),
      updatedAt: addDays(-1),
    },
  ];
};

export const crearReserva = async (reserva: Omit<Reserva, 'id' | 'createdAt' | 'updatedAt'>): Promise<Reserva> => {
  await new Promise(resolve => setTimeout(resolve, 500));
  
  return {
    ...reserva,
    id: Date.now().toString(),
    createdAt: new Date(),
    updatedAt: new Date(),
  };
};

export const actualizarReserva = async (id: string, reserva: Partial<Reserva>): Promise<Reserva> => {
  await new Promise(resolve => setTimeout(resolve, 500));
  
  return {
    id,
    clienteId: 'cliente1',
    clienteNombre: 'Juan Pérez',
    fecha: new Date(),
    horaInicio: '10:00',
    horaFin: '11:00',
    tipo: 'sesion-1-1',
    estado: 'confirmada',
    precio: 50,
    pagado: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    ...reserva,
  };
};

export const cancelarReserva = async (id: string, motivo?: string): Promise<Reserva> => {
  await new Promise(resolve => setTimeout(resolve, 500));
  
  return {
    id,
    clienteId: 'cliente1',
    clienteNombre: 'Juan Pérez',
    fecha: new Date(),
    horaInicio: '10:00',
    horaFin: '11:00',
    tipo: 'sesion-1-1',
    estado: 'cancelada',
    precio: 50,
    pagado: false,
    observaciones: motivo,
    createdAt: new Date(),
    updatedAt: new Date(),
  };
};

export const getClases = async (fechaInicio: Date, fechaFin: Date): Promise<Clase[]> => {
  await new Promise(resolve => setTimeout(resolve, 300));
  
  const hoy = new Date();
  const addDays = (days: number) => new Date(hoy.getTime() + days * 86400000);
  
  return [
    {
      id: 'clase1',
      nombre: 'Spinning',
      tipo: 'spinning',
      fecha: hoy,
      horaInicio: '10:00',
      horaFin: '11:00',
      capacidad: 20,
      ocupacion: 18,
      entrenadorId: 'entrenador1',
      entrenadorNombre: 'Elena Sánchez',
      salaId: 'sala1',
      salaNombre: 'Sala A',
      precio: 15,
      disponible: true,
    },
    {
      id: 'clase2',
      nombre: 'Boxeo',
      tipo: 'boxeo',
      fecha: hoy,
      horaInicio: '12:00',
      horaFin: '13:00',
      capacidad: 15,
      ocupacion: 12,
      entrenadorId: 'entrenador2',
      entrenadorNombre: 'Carlos López',
      salaId: 'sala2',
      salaNombre: 'Sala B',
      precio: 20,
      disponible: true,
    },
    {
      id: 'clase3',
      nombre: 'Spinning',
      tipo: 'spinning',
      fecha: addDays(1),
      horaInicio: '08:00',
      horaFin: '09:00',
      capacidad: 30,
      ocupacion: 28,
      entrenadorId: 'entrenador1',
      entrenadorNombre: 'Elena Sánchez',
      salaId: 'sala1',
      salaNombre: 'Sala A',
      precio: 15,
      disponible: true,
    },
    {
      id: 'clase4',
      nombre: 'Pilates',
      tipo: 'hiit',
      fecha: addDays(1),
      horaInicio: '18:30',
      horaFin: '19:30',
      capacidad: 15,
      ocupacion: 12,
      entrenadorId: 'entrenador3',
      entrenadorNombre: 'Roberto Martín',
      salaId: 'sala3',
      salaNombre: 'Sala C',
      precio: 18,
      disponible: true,
    },
    {
      id: 'clase5',
      nombre: 'HIIT',
      tipo: 'hiit',
      fecha: addDays(2),
      horaInicio: '19:00',
      horaFin: '20:00',
      capacidad: 20,
      ocupacion: 18,
      entrenadorId: 'entrenador2',
      entrenadorNombre: 'Carlos López',
      salaId: 'sala2',
      salaNombre: 'Sala B',
      precio: 20,
      disponible: true,
    },
    {
      id: 'clase6',
      nombre: 'Stretching',
      tipo: 'hiit',
      fecha: addDays(3),
      horaInicio: '09:00',
      horaFin: '10:00',
      capacidad: 18,
      ocupacion: 14,
      entrenadorId: 'entrenador4',
      entrenadorNombre: 'Laura Torres',
      salaId: 'sala3',
      salaNombre: 'Sala C',
      precio: 15,
      disponible: false,
    },
    {
      id: 'clase7',
      nombre: 'Fisioterapia',
      tipo: 'fisio',
      fecha: addDays(3),
      horaInicio: '11:00',
      horaFin: '12:00',
      capacidad: 1,
      ocupacion: 1,
      entrenadorId: 'entrenador5',
      entrenadorNombre: 'María González',
      salaId: 'sala4',
      salaNombre: 'Sala Fisioterapia',
      precio: 40,
      disponible: false,
    },
    {
      id: 'clase8',
      nombre: 'Consulta Nutricional',
      tipo: 'nutricion',
      fecha: addDays(4),
      horaInicio: '14:00',
      horaFin: '15:00',
      capacidad: 1,
      ocupacion: 1,
      entrenadorId: 'entrenador6',
      entrenadorNombre: 'Javier Ramos',
      salaId: 'sala5',
      salaNombre: 'Sala Nutrición',
      precio: 50,
      disponible: false,
    },
  ];
};
