import {
  AbsenceAutomation,
  AfterHoursAutoReply,
  AutomationRoadmapItem,
  ChannelHealthMetric,
  ClientReminderSettings,
  EmailProgram,
  ImportantDateAutomation,
  InactivityAutomation,
  LifecycleSequence,
  MessagingAutomation,
  MessageStatisticsDashboard,
  MessageTemplate,
  MissionControlSnapshot,
  MissionControlSummary,
  MultiChannelCampaign,
  PaymentReminderAutomation,
  PromotionalCampaign,
  ScheduledMessage,
  SessionReminder,
  SessionReminderTemplate,
  WelcomeSequence,
  ClientSegment,
  BulkMessage,
  Newsletter,
  NewsletterTemplate,
  ReservationsIntegration,
  CentralAutomationsPanel,
  MessageAlertsDashboard,
  PreferredSendingSchedulesDashboard,
  MultiStepSequence,
  ExportReport,
} from '../types';

const baseSummary: MissionControlSummary[] = [
  {
    id: 'messages-sent',
    label: 'Mensajes enviados',
    description: 'Total de mensajes enviados a clientes (30 días)',
    value: 1247,
    changePercentage: 15,
    trend: 'up',
    icon: 'workflow',
    channelFocus: 'multi',
  },
  {
    id: 'client-response-rate',
    label: 'Tasa de respuesta de clientes',
    description: 'Porcentaje de clientes que responden a mensajes',
    value: 68,
    changePercentage: 8,
    trend: 'up',
    icon: 'target',
    channelFocus: 'whatsapp',
  },
  {
    id: 'active-reminders',
    label: 'Recordatorios automáticos activos',
    description: 'Recordatorios de sesiones configurados y en funcionamiento',
    value: 42,
    changePercentage: 12,
    trend: 'up',
    icon: 'clock',
    channelFocus: 'sms',
  },
  {
    id: 'pending-communication',
    label: 'Clientes con comunicación pendiente',
    description: 'Clientes que requieren seguimiento o respuesta',
    value: 18,
    changePercentage: -22,
    trend: 'down',
    icon: 'target',
    channelFocus: 'multi',
  },
];

const multiChannelCampaigns: MultiChannelCampaign[] = [
  {
    id: 'cmp-omni-black-friday',
    name: 'Black Friday Omnicanal',
    objective: 'Reactivación y upsell de planes premium',
    status: 'running',
    owner: 'Growth Squad',
    launchDate: '2025-11-01',
    channels: ['email', 'sms', 'whatsapp', 'push'],
    targetSegments: ['Clientes inactivos', 'Usuarios premium trial', 'Leads calientes'],
    budget: 35000,
    spend: 18240,
    revenue: 76400,
    conversionRate: 7.4,
    progression: 62,
    nextAction: 'Test A/B de asunto con IA en segmento VIP',
    impactScore: 92,
  },
  {
    id: 'cmp-activacion-nov',
    name: 'Secuencia de activación leads Noviembre',
    objective: 'Conseguir primera compra en 7 días',
    status: 'running',
    owner: 'Lifecycle Ops',
    launchDate: '2025-10-26',
    channels: ['email', 'whatsapp', 'in-app'],
    targetSegments: ['Leads nuevos (≤14 días)', 'Referidos'],
    budget: 8200,
    spend: 3540,
    revenue: 15680,
    conversionRate: 4.9,
    progression: 48,
    nextAction: 'Activar paso de WhatsApp con CTA personalizada',
    impactScore: 78,
  },
  {
    id: 'cmp-retencion-premium',
    name: 'Retención planes premium Q4',
    objective: 'Reducir churn voluntario',
    status: 'scheduled',
    owner: 'Customer Marketing',
    launchDate: '2025-11-16',
    channels: ['email', 'sms'],
    targetSegments: ['Clientes premium 6+ meses', 'Usuarios con riesgo alto'],
    budget: 5400,
    spend: 0,
    revenue: 0,
    conversionRate: 0,
    progression: 28,
    nextAction: 'Sincronizar modelos de propensión de churn',
    impactScore: 84,
  },
];

const emailPrograms: EmailProgram[] = [
  {
    id: 'email-newsletter-semanal',
    name: 'Newsletter semanal “Mission Control”',
    type: 'newsletter',
    cadence: 'Semanal (jueves)',
    audienceSize: 18240,
    openRate: 41.2,
    clickRate: 9.6,
    revenueAttributed: 12600,
    bestSubject: '🎯 3 playbooks para reactivar leads fríos esta semana',
    status: 'running',
    aiRecommendation: 'Probar versión con bloque dinámico según segmento',
  },
  {
    id: 'email-product-update',
    name: 'Lanzamiento automatizaciones condicionales',
    type: 'product-update',
    cadence: 'Campaña puntual',
    audienceSize: 9200,
    openRate: 58.4,
    clickRate: 24.1,
    revenueAttributed: 18400,
    status: 'completed',
    aiRecommendation: 'Reutilizar como secuencia evergreen para leads enterprise',
  },
  {
    id: 'email-onboarding-fast-track',
    name: 'Fast-track Onboarding (Day 0-14)',
    type: 'onboarding',
    cadence: 'Automático',
    audienceSize: 4200,
    openRate: 72.6,
    clickRate: 18.3,
    revenueAttributed: 38600,
    status: 'running',
    aiRecommendation: 'Añadir video personalizado en paso 3 para mejorar activación',
  },
];

const lifecycleSequences: LifecycleSequence[] = [
  {
    id: 'lcsupsell-pro',
    name: 'Upsell a plan Pro tras 30 días activos',
    goal: 'upsell',
    steps: 7,
    activeContacts: 1380,
    completionRate: 63,
    avgTimeToConvert: 11,
    lastOptimization: '2025-10-28',
    bottleneckStep: 4,
    automationScore: 86,
    status: 'running',
  },
  {
    id: 'lcwinback-45',
    name: 'Winback 45 días inactivos',
    goal: 'winback',
    steps: 5,
    activeContacts: 820,
    completionRate: 47,
    avgTimeToConvert: 9,
    lastOptimization: '2025-09-18',
    automationScore: 72,
    status: 'running',
  },
  {
    id: 'lcchurnshield',
    name: 'Churn Shield Preventivo (riesgo alto)',
    goal: 'churn-prevention',
    steps: 8,
    activeContacts: 460,
    completionRate: 54,
    avgTimeToConvert: 6,
    lastOptimization: '2025-11-04',
    bottleneckStep: 6,
    automationScore: 88,
    status: 'running',
  },
];

const messagingAutomations: MessagingAutomation[] = [
  {
    id: 'auto-sms-pago',
    name: 'Recordatorio pago fallido + enlace one-click',
    trigger: 'Pago rechazado en Stripe',
    channel: 'sms',
    variantCount: 3,
    audienceSize: 420,
    responseRate: 42,
    SLA: '1m',
    status: 'running',
    lastTriggered: '2025-11-09T10:42:00Z',
    ownedBy: 'Revenue Ops',
    recommendedImprovement: 'Añadir fallback en WhatsApp si no hay respuesta en 2h',
  },
  {
    id: 'auto-whatsapp-demo',
    name: 'Confirmación demo + checklist interactivo',
    trigger: 'Demo agendada en CRM',
    channel: 'whatsapp',
    variantCount: 4,
    audienceSize: 188,
    responseRate: 78,
    SLA: 'Instantáneo',
    status: 'running',
    lastTriggered: '2025-11-09T11:05:00Z',
    ownedBy: 'Sales Enablement',
  },
  {
    id: 'auto-push-nps',
    name: 'Encuesta NPS post entrenamiento',
    trigger: 'Sesión completada (app móvil)',
    channel: 'push',
    variantCount: 2,
    audienceSize: 620,
    responseRate: 36,
    SLA: '30m',
    status: 'paused',
    lastTriggered: '2025-11-08T19:18:00Z',
    ownedBy: 'Customer Experience',
    recommendedImprovement: 'Reescribir copy + CTA con IA para elevar respuesta a 45%',
  },
];

const channelHealth: ChannelHealthMetric[] = [
  {
    id: 'health-email',
    channel: 'email',
    deliverability: 97,
    engagement: 68,
    satisfaction: 82,
    automationCoverage: 74,
    incidents: 1,
    highlight: 'Mantener warming de IP compartida para picos Black Friday',
  },
  {
    id: 'health-sms',
    channel: 'sms',
    deliverability: 93,
    engagement: 54,
    satisfaction: 77,
    automationCoverage: 61,
    incidents: 0,
    highlight: 'Probar mensajes cinemáticos con enlace trackeado y aceleración de respuesta',
  },
  {
    id: 'health-whatsapp',
    channel: 'whatsapp',
    deliverability: 99,
    engagement: 84,
    satisfaction: 90,
    automationCoverage: 88,
    incidents: 0,
    highlight: 'Nuevo template aprobado: “Plan personalizado con IA”',
  },
  {
    id: 'health-multi',
    channel: 'multi',
    deliverability: 95,
    engagement: 71,
    satisfaction: 85,
    automationCoverage: 79,
    incidents: 2,
    highlight: 'Sincronizar segmentos dinámicos cada 4h para evitar solapamiento',
  },
];

const roadmap: AutomationRoadmapItem[] = [
  {
    id: 'roadmap-ai-branching',
    title: 'Branching inteligente según comportamiento en app',
    description: 'Personalizar rutas de secuencias con IA usando eventos en tiempo real',
    owner: 'Automation Studio',
    impact: 'high',
    effort: 'L',
    eta: '2025-12-05',
    tags: ['IA', 'personalización', 'product-led'],
    status: 'in-progress',
  },
  {
    id: 'roadmap-bidireccional',
    title: 'Responder desde WhatsApp con macros dinámicas',
    description: 'Permitir respuesta humana asistida y mantener contexto en CRM',
    owner: 'Lifecycle Ops',
    impact: 'medium',
    effort: 'M',
    eta: '2025-11-28',
    tags: ['ventas', 'whatsapp', 'crm'],
    dependencies: ['roadmap-ai-branching'],
    status: 'ready',
  },
  {
    id: 'roadmap-voice',
    title: 'Activar canal de voice drops automatizados',
    description: 'Mensajes de voz personalizados para leads sin respuesta',
    owner: 'Growth Squad',
    impact: 'medium',
    effort: 'S',
    eta: '2025-12-12',
    tags: ['experimentación', 'nuevos-canales'],
    status: 'backlog',
  },
];

const sessionReminderTemplates: SessionReminderTemplate[] = [
  {
    id: 'reminder-24h-whatsapp',
    name: 'Recordatorio 24h antes - WhatsApp',
    description: 'Recordatorio estándar enviado 24 horas antes de la sesión',
    channel: 'whatsapp',
    messageTemplate: 'Hola {nombre}! 👋 Te recordamos que tienes una sesión mañana {fecha} a las {hora} en {lugar}. ¡Nos vemos pronto! 💪',
    timing: {
      type: 'before',
      hours: 24,
    },
    isActive: true,
    createdAt: '2025-10-15T10:00:00Z',
    updatedAt: '2025-11-01T14:30:00Z',
    variables: ['{nombre}', '{fecha}', '{hora}', '{lugar}'],
  },
  {
    id: 'reminder-2h-sms',
    name: 'Recordatorio 2h antes - SMS',
    description: 'Recordatorio de última hora 2 horas antes de la sesión',
    channel: 'sms',
    messageTemplate: 'Hola {nombre}, recordatorio: sesión hoy a las {hora}. Lugar: {lugar}. Confirma tu asistencia respondiendo SÍ.',
    timing: {
      type: 'before',
      hours: 2,
    },
    isActive: true,
    createdAt: '2025-10-15T10:00:00Z',
    updatedAt: '2025-11-01T14:30:00Z',
    variables: ['{nombre}', '{hora}', '{lugar}'],
  },
  {
    id: 'reminder-48h-email',
    name: 'Recordatorio 48h antes - Email',
    description: 'Recordatorio por email con detalles completos de la sesión',
    channel: 'email',
    messageTemplate: 'Hola {nombre},\n\nTe recordamos que tienes una sesión programada:\n\n📅 Fecha: {fecha}\n🕐 Hora: {hora}\n📍 Lugar: {lugar}\n\nPor favor, confirma tu asistencia o avísanos si necesitas reagendar.\n\n¡Nos vemos pronto!\n\nSaludos,\nTu entrenador personal',
    timing: {
      type: 'before',
      hours: 48,
    },
    isActive: true,
    createdAt: '2025-10-20T09:00:00Z',
    updatedAt: '2025-11-05T11:00:00Z',
    variables: ['{nombre}', '{fecha}', '{hora}', '{lugar}'],
  },
];

const clientReminderSettings: ClientReminderSettings[] = [
  {
    clientId: 'client-001',
    clientName: 'María González',
    templateId: 'reminder-24h-whatsapp',
    isEnabled: true,
    lastSent: '2025-11-08T10:00:00Z',
    nextScheduled: '2025-11-12T10:00:00Z',
  },
  {
    clientId: 'client-002',
    clientName: 'Juan Pérez',
    templateId: 'reminder-2h-sms',
    isEnabled: true,
    customMessage: 'Hola Juan! Recordatorio: sesión hoy a las {hora}. ¡No olvides traer tu botella de agua!',
    lastSent: '2025-11-09T08:00:00Z',
    nextScheduled: '2025-11-13T08:00:00Z',
  },
  {
    clientId: 'client-003',
    clientName: 'Ana Martínez',
    templateId: 'reminder-48h-email',
    isEnabled: true,
    lastSent: '2025-11-07T09:00:00Z',
    nextScheduled: '2025-11-11T09:00:00Z',
  },
  {
    clientId: 'client-004',
    clientName: 'Carlos Rodríguez',
    templateId: 'reminder-24h-whatsapp',
    isEnabled: false,
  },
];

const upcomingReminders: SessionReminder[] = [
  {
    id: 'reminder-upcoming-001',
    templateId: 'reminder-24h-whatsapp',
    templateName: 'Recordatorio 24h antes - WhatsApp',
    clientId: 'client-001',
    clientName: 'María González',
    sessionId: 'session-001',
    sessionDate: '2025-11-12',
    sessionTime: '10:00',
    channel: 'whatsapp',
    status: 'scheduled',
    scheduledAt: '2025-11-11T10:00:00Z',
    message: 'Hola María! 👋 Te recordamos que tienes una sesión mañana 12/11/2025 a las 10:00 en Gimnasio Central. ¡Nos vemos pronto! 💪',
  },
  {
    id: 'reminder-upcoming-002',
    templateId: 'reminder-2h-sms',
    templateName: 'Recordatorio 2h antes - SMS',
    clientId: 'client-002',
    clientName: 'Juan Pérez',
    sessionId: 'session-002',
    sessionDate: '2025-11-13',
    sessionTime: '18:00',
    channel: 'sms',
    status: 'scheduled',
    scheduledAt: '2025-11-13T16:00:00Z',
    message: 'Hola Juan, recordatorio: sesión hoy a las 18:00. Lugar: Gimnasio Central. Confirma tu asistencia respondiendo SÍ.',
  },
  {
    id: 'reminder-upcoming-003',
    templateId: 'reminder-48h-email',
    templateName: 'Recordatorio 48h antes - Email',
    clientId: 'client-003',
    clientName: 'Ana Martínez',
    sessionId: 'session-003',
    sessionDate: '2025-11-11',
    sessionTime: '09:00',
    channel: 'email',
    status: 'sent',
    scheduledAt: '2025-11-09T09:00:00Z',
    sentAt: '2025-11-09T09:00:00Z',
    message: 'Hola Ana,\n\nTe recordamos que tienes una sesión programada:\n\n📅 Fecha: 11/11/2025\n🕐 Hora: 09:00\n📍 Lugar: Gimnasio Central\n\nPor favor, confirma tu asistencia o avísanos si necesitas reagendar.\n\n¡Nos vemos pronto!\n\nSaludos,\nTu entrenador personal',
  },
];

// Secuencias de bienvenida - US-CA-003
const welcomeSequences: WelcomeSequence[] = [
  {
    id: 'welcome-seq-standard',
    name: 'Secuencia de Bienvenida Estándar',
    description: 'Secuencia automática de 3 días para nuevos clientes: bienvenida, qué esperar y preparación para la primera sesión',
    trigger: 'new-client',
    messages: [
      {
        id: 'welcome-msg-1',
        day: 1,
        title: 'Bienvenida',
        messageTemplate: '¡Hola {nombre}! 👋 Bienvenido/a a nuestro equipo. Estamos emocionados de comenzar este viaje contigo. En los próximos días te enviaremos información importante sobre tu primera sesión. ¡Nos vemos pronto! 💪',
        channel: 'whatsapp',
        scheduledTime: '09:00',
        variables: ['{nombre}'],
      },
      {
        id: 'welcome-msg-2',
        day: 2,
        title: 'Qué esperar',
        messageTemplate: 'Hola {nombre}, 👋\n\nMañana te contamos qué esperar en tu primera sesión. Por ahora, solo necesitas venir con ropa cómoda y muchas ganas. Si tienes alguna pregunta, no dudes en escribirme.\n\n¡Nos vemos pronto!',
        channel: 'whatsapp',
        scheduledTime: '10:00',
        variables: ['{nombre}'],
      },
      {
        id: 'welcome-msg-3',
        day: 3,
        title: 'Preparación primera sesión',
        messageTemplate: 'Hola {nombre}, 👋\n\nTu primera sesión está programada para {fechaPrimeraSesion} a las {horaPrimeraSesion}.\n\n📋 Recuerda traer:\n- Ropa cómoda\n- Botella de agua\n- Toalla\n\n📍 Lugar: {lugar}\n\nSi necesitas reagendar, avísame con al menos 24h de anticipación.\n\n¡Nos vemos mañana! 💪',
        channel: 'email',
        scheduledTime: '08:00',
        variables: ['{nombre}', '{fechaPrimeraSesion}', '{horaPrimeraSesion}', '{lugar}'],
      },
    ],
    activeClients: 24,
    completionRate: 78.5,
    status: 'running',
    createdAt: '2025-10-01T10:00:00Z',
    updatedAt: '2025-11-05T14:30:00Z',
  },
  {
    id: 'welcome-seq-premium',
    name: 'Secuencia de Bienvenida Premium',
    description: 'Secuencia extendida de 5 días para clientes premium con información adicional y recursos exclusivos',
    trigger: 'first-session-booked',
    messages: [
      {
        id: 'welcome-premium-1',
        day: 1,
        title: 'Bienvenida Premium',
        messageTemplate: '¡Hola {nombre}! 🎉 Bienvenido/a a nuestro programa Premium. Como cliente premium, tendrás acceso a recursos exclusivos y seguimiento personalizado. ¡Estamos aquí para ayudarte a alcanzar tus objetivos!',
        channel: 'email',
        scheduledTime: '09:00',
        variables: ['{nombre}'],
      },
      {
        id: 'welcome-premium-2',
        day: 2,
        title: 'Recursos exclusivos',
        messageTemplate: 'Hola {nombre}, 👋\n\nComo parte de tu programa Premium, tienes acceso a:\n- Plan nutricional personalizado\n- Videos de ejercicios exclusivos\n- Seguimiento 24/7\n\nRevisa tu email para acceder a estos recursos.',
        channel: 'email',
        scheduledTime: '10:00',
        variables: ['{nombre}'],
      },
      {
        id: 'welcome-premium-3',
        day: 3,
        title: 'Preparación primera sesión',
        messageTemplate: 'Hola {nombre}, 👋\n\nTu primera sesión está programada para {fechaPrimeraSesion} a las {horaPrimeraSesion}.\n\n📋 Checklist:\n- Ropa cómoda\n- Botella de agua\n- Toalla\n- Cuestionario de salud completado\n\n📍 Lugar: {lugar}\n\n¡Nos vemos pronto! 💪',
        channel: 'whatsapp',
        scheduledTime: '08:00',
        variables: ['{nombre}', '{fechaPrimeraSesion}', '{horaPrimeraSesion}', '{lugar}'],
      },
    ],
    activeClients: 8,
    completionRate: 92.3,
    status: 'running',
    createdAt: '2025-09-15T10:00:00Z',
    updatedAt: '2025-11-01T11:00:00Z',
  },
];

// Automatizaciones de ausencias - US-CA-004
const absenceAutomations: AbsenceAutomation[] = [
  {
    id: 'absence-auto-standard',
    name: 'Seguimiento de Ausencias Estándar',
    description: 'Detecta ausencias no justificadas y envía mensajes personalizados con diferentes tonos según la frecuencia de ausencias',
    isActive: true,
    messages: [
      {
        id: 'absence-msg-1',
        tone: 'friendly',
        absenceCount: 1,
        messageTemplate: 'Hola {nombre}! 👋 Notamos que no pudiste asistir a tu sesión de {fechaAusencia}. ¿Todo está bien? Si necesitas reagendar, puedes hacerlo respondiendo a este mensaje o usando este enlace: {opcionesReagendar}. ¡Estamos aquí para ayudarte!',
        channel: 'whatsapp',
        delayHours: 2,
        variables: ['{nombre}', '{fechaAusencia}', '{opcionesReagendar}'],
      },
      {
        id: 'absence-msg-2',
        tone: 'concerned',
        absenceCount: 2,
        messageTemplate: 'Hola {nombre}, 👋\n\nNotamos que has faltado a dos sesiones consecutivas. ¿Hay algo en lo que podamos ayudarte? Entendemos que pueden surgir imprevistos, pero queremos asegurarnos de que estés bien y que podamos ajustar tu plan si es necesario.\n\nPor favor, responde a este mensaje o reagenda tu próxima sesión aquí: {opcionesReagendar}\n\n¡Esperamos saber de ti pronto!',
        channel: 'email',
        delayHours: 4,
        variables: ['{nombre}', '{opcionesReagendar}'],
      },
      {
        id: 'absence-msg-3',
        tone: 'urgent',
        absenceCount: 3,
        messageTemplate: 'Hola {nombre},\n\nHemos notado que has faltado a varias sesiones. Queremos asegurarnos de que todo esté bien y que podamos ayudarte a retomar tu rutina de entrenamiento.\n\nPor favor, contáctanos lo antes posible para:\n- Reagendar tus sesiones\n- Ajustar tu plan si es necesario\n- Resolver cualquier problema que pueda estar impidiendo tu asistencia\n\nPuedes responder a este mensaje o llamarnos directamente. Estamos aquí para ayudarte a alcanzar tus objetivos.\n\n{opcionesReagendar}',
        channel: 'email',
        delayHours: 6,
        variables: ['{nombre}', '{opcionesReagendar}'],
      },
    ],
    activeCases: 12,
    responseRate: 65.5,
    reschedulingRate: 48.2,
    lastTriggered: '2025-11-09T14:30:00Z',
    createdAt: '2025-10-10T10:00:00Z',
    updatedAt: '2025-11-08T16:20:00Z',
  },
  {
    id: 'absence-auto-vip',
    name: 'Seguimiento de Ausencias VIP',
    description: 'Seguimiento personalizado para clientes VIP con contacto inmediato y opciones de reagendamiento prioritarias',
    isActive: true,
    messages: [
      {
        id: 'absence-vip-1',
        tone: 'friendly',
        absenceCount: 1,
        messageTemplate: 'Hola {nombre}! 👋 Como cliente VIP, notamos que no pudiste asistir a tu sesión. ¿Necesitas ayuda para reagendar? Como VIP, tienes prioridad en la agenda. Responde a este mensaje y te ayudamos de inmediato.',
        channel: 'whatsapp',
        delayHours: 1,
        variables: ['{nombre}', '{fechaAusencia}', '{opcionesReagendar}'],
      },
      {
        id: 'absence-vip-2',
        tone: 'concerned',
        absenceCount: 2,
        messageTemplate: 'Hola {nombre}, 👋\n\nComo cliente VIP, queremos asegurarnos de que recibas el mejor servicio. Hemos notado dos ausencias consecutivas. ¿Hay algo en lo que podamos ayudarte? Como VIP, podemos ajustar tu plan o tu horario según tus necesidades.\n\nPor favor, contáctanos para reagendar: {opcionesReagendar}',
        channel: 'whatsapp',
        delayHours: 2,
        variables: ['{nombre}', '{opcionesReagendar}'],
      },
    ],
    activeCases: 3,
    responseRate: 85.0,
    reschedulingRate: 72.5,
    lastTriggered: '2025-11-08T11:15:00Z',
    createdAt: '2025-09-20T10:00:00Z',
    updatedAt: '2025-11-05T09:30:00Z',
  },
];

function simulateLatency<T>(data: T, delay = 240): Promise<T> {
  return new Promise((resolve) => {
    setTimeout(() => resolve(JSON.parse(JSON.stringify(data)) as T), delay);
  });
}

export async function fetchMissionControlSummary(): Promise<MissionControlSummary[]> {
  return simulateLatency(baseSummary);
}

export async function fetchMultiChannelCampaigns(): Promise<MultiChannelCampaign[]> {
  return simulateLatency(multiChannelCampaigns);
}

export async function fetchEmailPrograms(): Promise<EmailProgram[]> {
  return simulateLatency(emailPrograms);
}

export async function fetchLifecycleSequences(): Promise<LifecycleSequence[]> {
  return simulateLatency(lifecycleSequences);
}

export async function fetchMessagingAutomations(): Promise<MessagingAutomation[]> {
  return simulateLatency(messagingAutomations);
}

export async function fetchChannelHealthMetrics(): Promise<ChannelHealthMetric[]> {
  return simulateLatency(channelHealth);
}

export async function fetchAutomationRoadmap(): Promise<AutomationRoadmapItem[]> {
  return simulateLatency(roadmap);
}

export async function fetchSessionReminderTemplates(): Promise<SessionReminderTemplate[]> {
  return simulateLatency(sessionReminderTemplates);
}

export async function fetchClientReminderSettings(): Promise<ClientReminderSettings[]> {
  return simulateLatency(clientReminderSettings);
}

export async function fetchUpcomingReminders(): Promise<SessionReminder[]> {
  return simulateLatency(upcomingReminders);
}

export async function fetchWelcomeSequences(): Promise<WelcomeSequence[]> {
  return simulateLatency(welcomeSequences);
}

export async function fetchAbsenceAutomations(): Promise<AbsenceAutomation[]> {
  return simulateLatency(absenceAutomations);
}

// Biblioteca de plantillas de mensajes - US-CA-005
const messageTemplates: MessageTemplate[] = [
  {
    id: 'template-confirmacion-sesion',
    name: 'Confirmación de Sesión',
    description: 'Plantilla para confirmar una sesión programada con el cliente',
    category: 'confirmacion-sesion',
    channel: 'whatsapp',
    messageTemplate: 'Hola {nombre}! 👋 Confirmamos tu sesión para el {fechaSesion} a las {horaSesion} en {lugar}. ¡Nos vemos pronto! 💪',
    variables: ['{nombre}', '{fechaSesion}', '{horaSesion}', '{lugar}'],
    usageCount: 145,
    lastUsed: '2025-11-09T10:30:00Z',
    createdAt: '2025-09-01T10:00:00Z',
    updatedAt: '2025-11-05T14:20:00Z',
    isFavorite: true,
    tags: ['sesión', 'confirmación'],
  },
  {
    id: 'template-recordatorio-pago',
    name: 'Recordatorio de Pago Pendiente',
    description: 'Recordatorio amable para clientes con pagos pendientes',
    category: 'recordatorio-pago',
    channel: 'whatsapp',
    messageTemplate: 'Hola {nombre}, 👋 Te recordamos que tienes un pago pendiente de {monto} con vencimiento el {fechaPago}. Puedes pagar aquí: {linkPago}. ¡Gracias!',
    variables: ['{nombre}', '{monto}', '{fechaPago}', '{linkPago}'],
    usageCount: 89,
    lastUsed: '2025-11-08T09:15:00Z',
    createdAt: '2025-09-10T10:00:00Z',
    updatedAt: '2025-11-01T11:30:00Z',
    isFavorite: true,
    tags: ['pago', 'recordatorio'],
  },
  {
    id: 'template-felicitacion-progreso',
    name: 'Felicitación por Progreso',
    description: 'Mensaje motivacional para felicitar a clientes por sus logros',
    category: 'felicitacion-progreso',
    channel: 'whatsapp',
    messageTemplate: '¡Felicidades {nombre}! 🎉 Has logrado {logro}. Estamos muy orgullosos de tu progreso. ¡Sigue así! 💪✨',
    variables: ['{nombre}', '{logro}'],
    usageCount: 67,
    lastUsed: '2025-11-07T16:45:00Z',
    createdAt: '2025-09-15T10:00:00Z',
    updatedAt: '2025-10-28T13:20:00Z',
    isFavorite: false,
    tags: ['motivación', 'progreso'],
  },
  {
    id: 'template-ajuste-plan',
    name: 'Sugerencia de Ajuste de Plan',
    description: 'Plantilla para sugerir ajustes en el plan de entrenamiento',
    category: 'ajuste-plan',
    channel: 'email',
    messageTemplate: 'Hola {nombre},\n\nBasándonos en tu progreso y objetivos, te sugerimos ajustar tu plan de entrenamiento.\n\n📋 Recomendaciones:\n- {recomendacion1}\n- {recomendacion2}\n\n¿Te gustaría agendar una sesión para revisar estos cambios?\n\nSaludos,\nTu entrenador personal',
    variables: ['{nombre}', '{recomendacion1}', '{recomendacion2}'],
    usageCount: 34,
    lastUsed: '2025-11-06T11:00:00Z',
    createdAt: '2025-09-20T10:00:00Z',
    updatedAt: '2025-11-02T09:15:00Z',
    isFavorite: false,
    tags: ['plan', 'ajuste'],
  },
  {
    id: 'template-bienvenida-general',
    name: 'Bienvenida General',
    description: 'Mensaje de bienvenida para nuevos clientes',
    category: 'bienvenida',
    channel: 'whatsapp',
    messageTemplate: '¡Hola {nombre}! 👋 Bienvenido/a a nuestro equipo. Estamos emocionados de comenzar este viaje contigo. Si tienes alguna pregunta, no dudes en escribirme. ¡Nos vemos pronto! 💪',
    variables: ['{nombre}'],
    usageCount: 123,
    lastUsed: '2025-11-09T08:30:00Z',
    createdAt: '2025-08-25T10:00:00Z',
    updatedAt: '2025-10-15T12:00:00Z',
    isFavorite: true,
    tags: ['bienvenida', 'nuevo-cliente'],
  },
  {
    id: 'template-seguimiento-general',
    name: 'Seguimiento General',
    description: 'Plantilla para seguimiento general con clientes',
    category: 'seguimiento',
    channel: 'whatsapp',
    messageTemplate: 'Hola {nombre}! 👋 ¿Cómo te sientes con tu entrenamiento? ¿Hay algo en lo que podamos ayudarte? ¡Estamos aquí para apoyarte! 💪',
    variables: ['{nombre}'],
    usageCount: 156,
    lastUsed: '2025-11-09T14:20:00Z',
    createdAt: '2025-09-05T10:00:00Z',
    updatedAt: '2025-11-03T10:45:00Z',
    isFavorite: false,
    tags: ['seguimiento', 'check-in'],
  },
];

// Sistema de mensajes programados - US-CA-006
const scheduledMessages: ScheduledMessage[] = [
  {
    id: 'scheduled-progreso-quincenal',
    name: 'Seguimiento de Progreso Quincenal',
    description: 'Mensaje automático cada 2 semanas preguntando por el progreso y cómo se sienten los clientes',
    templateId: 'template-seguimiento-general',
    messageContent: 'Hola {nombre}! 👋 Han pasado 2 semanas desde tu última sesión. ¿Cómo te sientes con tu progreso? ¿Hay algo en lo que podamos ayudarte? ¡Estamos aquí para apoyarte! 💪',
    channel: 'whatsapp',
    frequency: 'biweekly',
    recipients: [
      { type: 'group', id: 'group-activos', name: 'Clientes Activos' },
      { type: 'group', id: 'group-mensual', name: 'Plan Mensual' },
    ],
    nextScheduledDate: '2025-11-23T10:00:00Z',
    lastSentDate: '2025-11-09T10:00:00Z',
    status: 'running',
    totalSent: 48,
    responseRate: 72.5,
    isActive: true,
    createdAt: '2025-10-01T10:00:00Z',
    updatedAt: '2025-11-09T10:00:00Z',
    variables: ['{nombre}'],
  },
  {
    id: 'scheduled-progreso-mensual',
    name: 'Check-in Mensual de Progreso',
    description: 'Mensaje mensual para revisar objetivos y ajustar el plan si es necesario',
    messageContent: 'Hola {nombre}! 👋 Este mes queremos revisar contigo tu progreso y objetivos. ¿Cómo te sientes? ¿Hay algo que quieras ajustar en tu plan? ¡Agenda una sesión de revisión cuando quieras! 💪',
    channel: 'email',
    frequency: 'monthly',
    recipients: [
      { type: 'group', id: 'group-premium', name: 'Clientes Premium' },
    ],
    nextScheduledDate: '2025-12-01T09:00:00Z',
    lastSentDate: '2025-11-01T09:00:00Z',
    status: 'running',
    totalSent: 12,
    responseRate: 58.3,
    isActive: true,
    createdAt: '2025-09-15T10:00:00Z',
    updatedAt: '2025-11-01T09:00:00Z',
    variables: ['{nombre}'],
  },
  {
    id: 'scheduled-motivacion-semanal',
    name: 'Motivación Semanal',
    description: 'Mensaje motivacional semanal para mantener el engagement',
    messageContent: '¡Hola {nombre}! 💪 Nueva semana, nuevas oportunidades. Recuerda que cada pequeño paso cuenta. ¡Sigue adelante! 🌟',
    channel: 'whatsapp',
    frequency: 'weekly',
    recipients: [
      { type: 'client', id: 'client-001', name: 'María González' },
      { type: 'client', id: 'client-002', name: 'Juan Pérez' },
      { type: 'group', id: 'group-inicio', name: 'Clientes Nuevos' },
    ],
    nextScheduledDate: '2025-11-16T08:00:00Z',
    lastSentDate: '2025-11-09T08:00:00Z',
    status: 'running',
    totalSent: 24,
    responseRate: 45.8,
    isActive: true,
    createdAt: '2025-10-20T10:00:00Z',
    updatedAt: '2025-11-09T08:00:00Z',
    variables: ['{nombre}'],
  },
  {
    id: 'scheduled-seguimiento-custom',
    name: 'Seguimiento Personalizado',
    description: 'Mensaje cada 10 días para clientes específicos que requieren seguimiento más frecuente',
    messageContent: 'Hola {nombre}! 👋 Queríamos hacer un seguimiento contigo. ¿Cómo va todo? ¿Necesitas algo? ¡Estamos aquí para ayudarte! 💪',
    channel: 'whatsapp',
    frequency: 'custom',
    customFrequencyDays: 10,
    recipients: [
      { type: 'client', id: 'client-003', name: 'Ana Martínez' },
      { type: 'client', id: 'client-004', name: 'Carlos Rodríguez' },
    ],
    nextScheduledDate: '2025-11-19T10:00:00Z',
    lastSentDate: '2025-11-09T10:00:00Z',
    status: 'running',
    totalSent: 6,
    responseRate: 83.3,
    isActive: true,
    createdAt: '2025-10-25T10:00:00Z',
    updatedAt: '2025-11-09T10:00:00Z',
    variables: ['{nombre}'],
  },
  {
    id: 'scheduled-recordatorio-diario',
    name: 'Recordatorio Diario de Ejercicios',
    description: 'Recordatorio diario para clientes que tienen ejercicios para hacer en casa',
    messageContent: '¡Buenos días {nombre}! ☀️ Recuerda hacer tus ejercicios de hoy. ¡Tú puedes! 💪',
    channel: 'whatsapp',
    frequency: 'daily',
    recipients: [
      { type: 'group', id: 'group-ejercicios-casa', name: 'Ejercicios en Casa' },
    ],
    nextScheduledDate: '2025-11-10T07:00:00Z',
    lastSentDate: '2025-11-09T07:00:00Z',
    status: 'paused',
    totalSent: 15,
    responseRate: 33.3,
    isActive: false,
    createdAt: '2025-11-01T10:00:00Z',
    updatedAt: '2025-11-08T12:00:00Z',
    variables: ['{nombre}'],
  },
];

export async function fetchMessageTemplates(): Promise<MessageTemplate[]> {
  return simulateLatency(messageTemplates);
}

export async function fetchScheduledMessages(): Promise<ScheduledMessage[]> {
  return simulateLatency(scheduledMessages);
}

// Automatización de inactividad - US-CA-007
const inactivityAutomations: InactivityAutomation[] = [
  {
    id: 'inactivity-auto-standard',
    name: 'Reactivación de Clientes Inactivos',
    description: 'Secuencia progresiva para clientes sin sesiones en 14 días: mensajes motivacionales, ofertas especiales e invitaciones a retomar',
    inactivityThresholdDays: 14,
    messages: [
      {
        id: 'inactivity-msg-1',
        step: 1,
        type: 'check-in',
        daysAfterInactivity: 0,
        messageTemplate: 'Hola {nombre}! 👋 Notamos que hace {diasInactivo} días que no tienes sesión. ¿Todo está bien? Estamos aquí para ayudarte a retomar tu rutina. 💪',
        channel: 'whatsapp',
        scheduledTime: '10:00',
        variables: ['{nombre}', '{diasInactivo}'],
        pauseOnResponse: true,
      },
      {
        id: 'inactivity-msg-2',
        step: 2,
        type: 'motivational',
        daysAfterInactivity: 3,
        messageTemplate: '¡Hola {nombre}! 💪 Recuerda que cada pequeño paso cuenta. Tu última sesión fue el {ultimaSesion}. ¿Te gustaría agendar una sesión esta semana? ¡Estamos aquí para apoyarte!',
        channel: 'whatsapp',
        scheduledTime: '09:00',
        variables: ['{nombre}', '{ultimaSesion}'],
        pauseOnResponse: true,
      },
      {
        id: 'inactivity-msg-3',
        step: 3,
        type: 'special-offer',
        daysAfterInactivity: 7,
        messageTemplate: 'Hola {nombre}! 🎁 Como valoramos tu compromiso, tenemos una oferta especial para ti: {ofertaEspecial}. Válida hasta el {fechaVencimiento}. ¡No dejes pasar esta oportunidad!',
        channel: 'email',
        scheduledTime: '08:00',
        variables: ['{nombre}', '{ofertaEspecial}', '{fechaVencimiento}'],
        pauseOnResponse: true,
      },
      {
        id: 'inactivity-msg-4',
        step: 4,
        type: 'invitation',
        daysAfterInactivity: 14,
        messageTemplate: '¡Hola {nombre}! 👋 Te extrañamos. Queremos invitarte a retomar tu entrenamiento. Agenda tu próxima sesión y recibe una sesión adicional gratis. ¡Es momento de volver! 💪',
        channel: 'whatsapp',
        scheduledTime: '10:00',
        variables: ['{nombre}'],
        pauseOnResponse: true,
      },
    ],
    activeClients: 18,
    pausedClients: 5,
    responseRate: 58.3,
    reactivationRate: 42.1,
    isActive: true,
    lastTriggered: '2025-11-09T10:00:00Z',
    createdAt: '2025-10-15T10:00:00Z',
    updatedAt: '2025-11-08T14:30:00Z',
  },
  {
    id: 'inactivity-auto-extended',
    name: 'Reactivación Extendida (30 días)',
    description: 'Secuencia extendida para clientes inactivos por 30 días con mensajes más intensivos y ofertas especiales',
    inactivityThresholdDays: 30,
    messages: [
      {
        id: 'inactivity-ext-1',
        step: 1,
        type: 'check-in',
        daysAfterInactivity: 0,
        messageTemplate: 'Hola {nombre}! 👋 Hace {diasInactivo} días que no nos vemos. ¿Cómo estás? Queremos saber si todo está bien y cómo podemos ayudarte.',
        channel: 'email',
        scheduledTime: '09:00',
        variables: ['{nombre}', '{diasInactivo}'],
        pauseOnResponse: true,
      },
      {
        id: 'inactivity-ext-2',
        step: 2,
        type: 'motivational',
        daysAfterInactivity: 5,
        messageTemplate: '¡Hola {nombre}! 💪 Sabemos que retomar puede ser difícil, pero estamos aquí para ayudarte. Tu progreso anterior fue increíble. ¿Qué te parece si agendamos una sesión de reintroducción?',
        channel: 'whatsapp',
        scheduledTime: '10:00',
        variables: ['{nombre}'],
        pauseOnResponse: true,
      },
      {
        id: 'inactivity-ext-3',
        step: 3,
        type: 'special-offer',
        daysAfterInactivity: 10,
        messageTemplate: 'Hola {nombre}! 🎁 Oferta especial de reactivación: {ofertaEspecial}. Válida solo por tiempo limitado. ¡Es el momento perfecto para retomar!',
        channel: 'email',
        scheduledTime: '08:00',
        variables: ['{nombre}', '{ofertaEspecial}'],
        pauseOnResponse: true,
      },
      {
        id: 'inactivity-ext-4',
        step: 4,
        type: 'invitation',
        daysAfterInactivity: 20,
        messageTemplate: '¡Hola {nombre}! 👋 Te invitamos a una sesión de prueba gratuita. Sin compromiso, solo para que veas cómo te sientes. ¿Te animas?',
        channel: 'whatsapp',
        scheduledTime: '10:00',
        variables: ['{nombre}'],
        pauseOnResponse: true,
      },
    ],
    activeClients: 8,
    pausedClients: 2,
    responseRate: 45.0,
    reactivationRate: 28.5,
    isActive: true,
    lastTriggered: '2025-11-08T09:30:00Z',
    createdAt: '2025-09-20T10:00:00Z',
    updatedAt: '2025-11-05T11:00:00Z',
  },
];

// Sistema de fechas importantes - US-CA-008
const importantDateAutomations: ImportantDateAutomation[] = [
  {
    id: 'important-dates-standard',
    name: 'Fechas Importantes Estándar',
    description: 'Sistema que detecta cumpleaños, aniversarios y fechas importantes de cada cliente y envía mensajes personalizados automáticamente',
    messages: [
      {
        id: 'date-msg-birthday',
        dateType: 'birthday',
        messageTemplate: '¡Feliz cumpleaños {nombre}! 🎉🎂 Esperamos que tengas un día increíble. Como regalo especial, tienes {ofertaEspecial}. ¡Que cumplas muchos más! 💪✨',
        channel: 'whatsapp',
        includeSpecialOffer: true,
        specialOfferTemplate: '20% de descuento en tu próxima sesión o bono de 3 sesiones',
        includeSessionReminder: false,
        sendTime: '09:00',
        sendDaysBefore: 0,
        variables: ['{nombre}', '{edad}', '{ofertaEspecial}'],
      },
      {
        id: 'date-msg-anniversary',
        dateType: 'anniversary',
        messageTemplate: '¡Feliz aniversario {nombre}! 🎉 Hace {añosEntrenando} años que comenzamos este viaje juntos. Gracias por confiar en nosotros. Como agradecimiento, {ofertaEspecial}. ¡Seguimos juntos! 💪',
        channel: 'email',
        includeSpecialOffer: true,
        specialOfferTemplate: 'Sesión gratuita o 15% de descuento en tu próximo plan',
        includeSessionReminder: true,
        sendTime: '10:00',
        sendDaysBefore: 0,
        variables: ['{nombre}', '{añosEntrenando}', '{ofertaEspecial}'],
      },
      {
        id: 'date-msg-milestone',
        dateType: 'milestone',
        messageTemplate: '¡Felicidades {nombre}! 🎉 Has alcanzado un hito importante: {milestone}. Estamos muy orgullosos de tu progreso. ¡Sigue así! 💪✨',
        channel: 'whatsapp',
        includeSpecialOffer: false,
        includeSessionReminder: false,
        sendTime: '09:00',
        sendDaysBefore: 0,
        variables: ['{nombre}', '{milestone}'],
      },
    ],
    activeDates: 45,
    upcomingDates: 8,
    sentThisMonth: 12,
    responseRate: 78.5,
    isActive: true,
    lastTriggered: '2025-11-09T09:00:00Z',
    createdAt: '2025-09-01T10:00:00Z',
    updatedAt: '2025-11-08T15:20:00Z',
  },
  {
    id: 'important-dates-premium',
    name: 'Fechas Importantes Premium',
    description: 'Sistema premium con mensajes más personalizados y ofertas exclusivas para clientes VIP',
    messages: [
      {
        id: 'date-premium-birthday',
        dateType: 'birthday',
        messageTemplate: '¡Feliz cumpleaños {nombre}! 🎉🎂 Como cliente VIP, queremos hacer tu día especial. {ofertaEspecial}. Además, agenda tu sesión de esta semana y recibe un regalo sorpresa. ¡Que cumplas muchos más! 💪✨',
        channel: 'whatsapp',
        includeSpecialOffer: true,
        specialOfferTemplate: 'Sesión gratuita + 25% de descuento en productos',
        includeSessionReminder: true,
        sendTime: '08:00',
        sendDaysBefore: 1,
        variables: ['{nombre}', '{edad}', '{ofertaEspecial}'],
      },
      {
        id: 'date-premium-anniversary',
        dateType: 'anniversary',
        messageTemplate: '¡Feliz aniversario {nombre}! 🎉 Hace {añosEntrenando} años que eres parte de nuestra familia VIP. Gracias por tu lealtad. {ofertaEspecial}. ¡Celebremos juntos! 💪',
        channel: 'email',
        includeSpecialOffer: true,
        specialOfferTemplate: 'Bono de 2 sesiones gratis + plan personalizado actualizado',
        includeSessionReminder: true,
        sendTime: '09:00',
        sendDaysBefore: 0,
        variables: ['{nombre}', '{añosEntrenando}', '{ofertaEspecial}'],
      },
    ],
    activeDates: 12,
    upcomingDates: 2,
    sentThisMonth: 3,
    responseRate: 91.7,
    isActive: true,
    lastTriggered: '2025-11-08T08:00:00Z',
    createdAt: '2025-09-15T10:00:00Z',
    updatedAt: '2025-11-05T10:30:00Z',
  },
];

export async function fetchInactivityAutomations(): Promise<InactivityAutomation[]> {
  return simulateLatency(inactivityAutomations);
}

export async function fetchImportantDateAutomations(): Promise<ImportantDateAutomation[]> {
  return simulateLatency(importantDateAutomations);
}

// Automatización de recordatorios de pagos - US-CA-009
const paymentReminderAutomations: PaymentReminderAutomation[] = [
  {
    id: 'payment-reminder-standard',
    name: 'Recordatorios de Pago Estándar',
    description: 'Automatización que detecta pagos pendientes o próximos a vencer y envía recordatorios amables por WhatsApp o email, con diferentes mensajes según los días de retraso',
    messages: [
      {
        id: 'payment-msg-1',
        daysDelay: 0,
        tone: 'friendly',
        messageTemplate: 'Hola {nombre}! 👋 Te recordamos que tienes un pago próximo a vencer el {fechaVencimiento} por un monto de {monto}. Puedes pagar fácilmente aquí: {linkPago}. ¡Gracias por tu confianza! 💪',
        channel: 'whatsapp',
        sendTime: '09:00',
        variables: ['{nombre}', '{fechaVencimiento}', '{monto}', '{linkPago}'],
      },
      {
        id: 'payment-msg-2',
        daysDelay: 1,
        tone: 'friendly',
        messageTemplate: 'Hola {nombre}, 👋\n\nNotamos que tu pago de {monto} con vencimiento el {fechaVencimiento} está vencido desde ayer. ¿Necesitas ayuda para realizar el pago? Puedes hacerlo aquí: {linkPago}\n\n¡Estamos aquí para ayudarte!',
        channel: 'whatsapp',
        sendTime: '10:00',
        variables: ['{nombre}', '{monto}', '{fechaVencimiento}', '{linkPago}'],
      },
      {
        id: 'payment-msg-3',
        daysDelay: 3,
        tone: 'gentle',
        messageTemplate: 'Hola {nombre},\n\nTu pago de {monto} tiene {diasRetraso} días de retraso. Para continuar disfrutando de nuestros servicios, te pedimos que realices el pago lo antes posible.\n\nPuedes pagar aquí: {linkPago}\n\nSi tienes alguna dificultad, no dudes en contactarnos. ¡Estamos aquí para ayudarte!',
        channel: 'email',
        sendTime: '09:00',
        variables: ['{nombre}', '{monto}', '{diasRetraso}', '{linkPago}'],
      },
      {
        id: 'payment-msg-4',
        daysDelay: 7,
        tone: 'urgent',
        messageTemplate: 'Hola {nombre},\n\nTu pago de {monto} tiene {diasRetraso} días de retraso. Es importante que regularices tu situación para evitar la suspensión de servicios.\n\nPor favor, realiza el pago aquí: {linkPago}\n\nSi necesitas ayuda o tienes alguna dificultad, contáctanos de inmediato. Estamos aquí para encontrar una solución juntos.',
        channel: 'email',
        sendTime: '08:00',
        variables: ['{nombre}', '{monto}', '{diasRetraso}', '{linkPago}'],
      },
    ],
    activeReminders: 24,
    sentThisMonth: 156,
    paymentRecoveryRate: 68.5,
    responseRate: 72.3,
    isActive: true,
    lastTriggered: '2025-11-09T09:15:00Z',
    createdAt: '2025-10-01T10:00:00Z',
    updatedAt: '2025-11-08T14:20:00Z',
  },
  {
    id: 'payment-reminder-premium',
    name: 'Recordatorios de Pago Premium',
    description: 'Recordatorios personalizados para clientes premium con mensajes más cercanos y opciones de pago flexibles',
    messages: [
      {
        id: 'payment-premium-1',
        daysDelay: 0,
        tone: 'friendly',
        messageTemplate: 'Hola {nombre}! 👋 Como cliente Premium, queremos recordarte que tu pago de {monto} vence el {fechaVencimiento}. Puedes pagar aquí: {linkPago}. ¡Gracias por ser parte de nuestra familia Premium! 💎',
        channel: 'whatsapp',
        sendTime: '09:00',
        variables: ['{nombre}', '{monto}', '{fechaVencimiento}', '{linkPago}'],
      },
      {
        id: 'payment-premium-2',
        daysDelay: 2,
        tone: 'gentle',
        messageTemplate: 'Hola {nombre}, 👋\n\nComo cliente Premium, notamos que tu pago de {monto} tiene 2 días de retraso. Como valoramos nuestra relación, queremos ayudarte. ¿Necesitas alguna flexibilidad en el pago? Contáctanos y encontraremos una solución.\n\nPuedes pagar aquí: {linkPago}',
        channel: 'whatsapp',
        sendTime: '10:00',
        variables: ['{nombre}', '{monto}', '{linkPago}'],
      },
    ],
    activeReminders: 8,
    sentThisMonth: 42,
    paymentRecoveryRate: 85.2,
    responseRate: 88.5,
    isActive: true,
    lastTriggered: '2025-11-09T09:00:00Z',
    createdAt: '2025-09-15T10:00:00Z',
    updatedAt: '2025-11-05T11:30:00Z',
  },
];

// Dashboard de estadísticas de mensajes - US-CA-010
const messageStatisticsDashboard: MessageStatisticsDashboard = {
  totalMessagesSent: 1247,
  totalMessagesOpened: 856,
  totalMessagesReplied: 623,
  overallOpenRate: 68.6,
  overallReplyRate: 49.9,
  period: '30d',
  lastUpdated: '2025-11-09T12:00:00Z',
  statistics: [
    {
      id: 'stat-recordatorio-sesion',
      messageType: 'recordatorio-sesion',
      typeLabel: 'Recordatorios de Sesión',
      totalSent: 342,
      totalOpened: 298,
      totalReplied: 187,
      openRate: 87.1,
      replyRate: 54.7,
      channel: 'whatsapp',
      period: '30d',
      trend: 'up',
      changePercentage: 5.2,
    },
    {
      id: 'stat-recordatorio-pago',
      messageType: 'recordatorio-pago',
      typeLabel: 'Recordatorios de Pago',
      totalSent: 156,
      totalOpened: 124,
      totalReplied: 98,
      openRate: 79.5,
      replyRate: 62.8,
      channel: 'whatsapp',
      period: '30d',
      trend: 'up',
      changePercentage: 8.3,
    },
    {
      id: 'stat-bienvenida',
      messageType: 'bienvenida',
      typeLabel: 'Bienvenida',
      totalSent: 48,
      totalOpened: 42,
      totalReplied: 35,
      openRate: 87.5,
      replyRate: 72.9,
      channel: 'whatsapp',
      period: '30d',
      trend: 'neutral',
      changePercentage: 0.0,
    },
    {
      id: 'stat-seguimiento',
      messageType: 'seguimiento',
      typeLabel: 'Seguimiento',
      totalSent: 234,
      totalOpened: 168,
      totalReplied: 112,
      openRate: 71.8,
      replyRate: 47.9,
      channel: 'whatsapp',
      period: '30d',
      trend: 'down',
      changePercentage: -3.1,
    },
    {
      id: 'stat-ausencia',
      messageType: 'ausencia',
      typeLabel: 'Ausencias',
      totalSent: 89,
      totalOpened: 67,
      totalReplied: 52,
      openRate: 75.3,
      replyRate: 58.4,
      channel: 'email',
      period: '30d',
      trend: 'up',
      changePercentage: 4.7,
    },
    {
      id: 'stat-inactividad',
      messageType: 'inactividad',
      typeLabel: 'Inactividad',
      totalSent: 156,
      totalOpened: 98,
      totalReplied: 64,
      openRate: 62.8,
      replyRate: 41.0,
      channel: 'email',
      period: '30d',
      trend: 'up',
      changePercentage: 6.2,
    },
    {
      id: 'stat-fecha-importante',
      messageType: 'fecha-importante',
      typeLabel: 'Fechas Importantes',
      totalSent: 45,
      totalOpened: 38,
      totalReplied: 32,
      openRate: 84.4,
      replyRate: 71.1,
      channel: 'whatsapp',
      period: '30d',
      trend: 'up',
      changePercentage: 2.5,
    },
    {
      id: 'stat-programado',
      messageType: 'programado',
      typeLabel: 'Programados',
      totalSent: 177,
      totalOpened: 121,
      totalReplied: 43,
      openRate: 68.4,
      replyRate: 24.3,
      channel: 'email',
      period: '30d',
      trend: 'down',
      changePercentage: -5.8,
    },
  ],
};

export async function fetchPaymentReminderAutomations(): Promise<PaymentReminderAutomation[]> {
  return simulateLatency(paymentReminderAutomations);
}

export async function fetchMessageStatisticsDashboard(): Promise<MessageStatisticsDashboard> {
  return simulateLatency(messageStatisticsDashboard);
}

// US-CA-011: Sistema de segmentación
const clientSegments: ClientSegment[] = [
  {
    id: 'seg-inactivos-30d',
    name: 'Clientes inactivos 30+ días',
    description: 'Clientes que no han asistido a sesiones en los últimos 30 días',
    criteria: [
      {
        id: 'crit-1',
        type: 'days-since-last-session',
        operator: 'greater-than',
        value: 30,
        label: 'Última sesión hace más de 30 días',
      },
    ],
    clientCount: 24,
    lastUpdated: '2025-01-15T10:00:00Z',
    createdAt: '2025-01-01T08:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    isActive: true,
    tags: ['inactivos', 'retención'],
  },
  {
    id: 'seg-plan-mensual',
    name: 'Clientes con plan mensual',
    description: 'Todos los clientes con plan de pago mensual activo',
    criteria: [
      {
        id: 'crit-2',
        type: 'plan-type',
        operator: 'equals',
        value: 'mensual',
        label: 'Plan tipo: Mensual',
      },
    ],
    clientCount: 156,
    lastUpdated: '2025-01-15T10:00:00Z',
    createdAt: '2025-01-01T08:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    isActive: true,
    tags: ['plan', 'mensual'],
  },
  {
    id: 'seg-alta-adherencia',
    name: 'Clientes con alta adherencia',
    description: 'Clientes con tasa de adherencia superior al 80%',
    criteria: [
      {
        id: 'crit-3',
        type: 'adherence-rate',
        operator: 'greater-than',
        value: 80,
        label: 'Adherencia mayor a 80%',
      },
    ],
    clientCount: 89,
    lastUpdated: '2025-01-15T10:00:00Z',
    createdAt: '2025-01-01T08:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    isActive: true,
    tags: ['adherencia', 'alto-engagement'],
  },
  {
    id: 'seg-pago-pendiente',
    name: 'Pagos pendientes',
    description: 'Clientes con pagos pendientes o vencidos',
    criteria: [
      {
        id: 'crit-4',
        type: 'payment-status',
        operator: 'in',
        value: ['pending', 'overdue'],
        label: 'Estado de pago: Pendiente o Vencido',
      },
    ],
    clientCount: 12,
    lastUpdated: '2025-01-15T10:00:00Z',
    createdAt: '2025-01-01T08:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    isActive: true,
    tags: ['pagos', 'urgente'],
  },
];

const bulkMessages: BulkMessage[] = [
  {
    id: 'bulk-msg-reactivacion',
    name: 'Campaña de reactivación Q1',
    description: 'Mensaje motivacional para clientes inactivos',
    segmentId: 'seg-inactivos-30d',
    segmentName: 'Clientes inactivos 30+ días',
    messageTemplate: 'Hola {nombre}, notamos que hace tiempo que no nos vemos. ¿Te gustaría reagendar tu próxima sesión?',
    channel: 'whatsapp',
    variables: ['nombre', 'ultimaSesion'],
    status: 'completed',
    sentDate: '2025-01-10T09:00:00Z',
    totalRecipients: 24,
    sentCount: 24,
    deliveredCount: 23,
    openedCount: 18,
    repliedCount: 8,
    deliveryRate: 95.8,
    openRate: 75.0,
    replyRate: 33.3,
    createdAt: '2025-01-08T08:00:00Z',
    updatedAt: '2025-01-10T09:30:00Z',
  },
  {
    id: 'bulk-msg-nuevo-plan',
    name: 'Oferta plan trimestral',
    description: 'Promoción especial para clientes mensuales',
    segmentId: 'seg-plan-mensual',
    segmentName: 'Clientes con plan mensual',
    messageTemplate: 'Hola {nombre}, tenemos una oferta especial para ti. Cambia a plan trimestral y ahorra 15%.',
    channel: 'email',
    variables: ['nombre', 'plan'],
    status: 'scheduled',
    scheduledDate: '2025-01-20T10:00:00Z',
    totalRecipients: 156,
    sentCount: 0,
    deliveredCount: 0,
    openedCount: 0,
    repliedCount: 0,
    deliveryRate: 0,
    openRate: 0,
    replyRate: 0,
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '2025-01-15T08:00:00Z',
  },
];

export async function fetchClientSegments(): Promise<ClientSegment[]> {
  return simulateLatency(clientSegments);
}

export async function fetchBulkMessages(): Promise<BulkMessage[]> {
  return simulateLatency(bulkMessages);
}

// US-CA-012: Editor de newsletters
const newsletterTemplates: NewsletterTemplate[] = [
  {
    id: 'template-fitness-tips',
    name: 'Tips de Fitness Semanal',
    description: 'Plantilla para newsletter semanal con consejos de entrenamiento',
    category: 'fitness-tips',
    htmlContent: '<html><body><h1>Tips de Fitness</h1><p>Contenido del newsletter...</p></body></html>',
    isDefault: true,
    createdAt: '2025-01-01T08:00:00Z',
    updatedAt: '2025-01-01T08:00:00Z',
  },
  {
    id: 'template-nutricion',
    name: 'Newsletter de Nutrición',
    description: 'Plantilla enfocada en consejos nutricionales',
    category: 'nutrition',
    htmlContent: '<html><body><h1>Nutrición</h1><p>Contenido del newsletter...</p></body></html>',
    isDefault: false,
    createdAt: '2025-01-01T08:00:00Z',
    updatedAt: '2025-01-01T08:00:00Z',
  },
  {
    id: 'template-success-stories',
    name: 'Historias de Éxito',
    description: 'Plantilla para destacar transformaciones de clientes',
    category: 'success-stories',
    htmlContent: '<html><body><h1>Historias de Éxito</h1><p>Contenido del newsletter...</p></body></html>',
    isDefault: false,
    createdAt: '2025-01-01T08:00:00Z',
    updatedAt: '2025-01-01T08:00:00Z',
  },
];

const newsletters: Newsletter[] = [
  {
    id: 'newsletter-semanal-enero',
    name: 'Newsletter Semanal - Enero',
    description: 'Newsletter semanal con tips de fitness y motivación',
    subject: '🎯 Tips de esta semana para alcanzar tus objetivos',
    templateId: 'template-fitness-tips',
    htmlContent: '<html><body><h1>Tips de Fitness</h1><p>Contenido personalizado...</p></body></html>',
    segmentId: 'seg-alta-adherencia',
    segmentName: 'Clientes con alta adherencia',
    schedule: {
      id: 'schedule-1',
      frequency: 'weekly',
      dayOfWeek: 3, // Miércoles
      time: '09:00',
      timezone: 'America/Mexico_City',
      nextScheduledDate: '2025-01-22T09:00:00Z',
      lastSentDate: '2025-01-15T09:00:00Z',
      isActive: true,
    },
    status: 'scheduled',
    tracking: {
      id: 'track-1',
      newsletterId: 'newsletter-semanal-enero',
      sentDate: '2025-01-15T09:00:00Z',
      totalRecipients: 89,
      deliveredCount: 87,
      openedCount: 52,
      uniqueOpens: 48,
      clickedCount: 18,
      uniqueClicks: 16,
      unsubscribedCount: 1,
      bouncedCount: 2,
      deliveryRate: 97.8,
      openRate: 58.4,
      clickRate: 20.2,
      clickToOpenRate: 34.6,
      unsubscribeRate: 1.1,
      bounceRate: 2.2,
      topLinks: [
        { url: 'https://example.com/tips', clicks: 12, uniqueClicks: 11 },
        { url: 'https://example.com/retos', clicks: 6, uniqueClicks: 5 },
      ],
      deviceBreakdown: {
        desktop: 28,
        mobile: 20,
        tablet: 4,
      },
    },
    totalSent: 3,
    averageOpenRate: 58.4,
    averageClickRate: 20.2,
    createdAt: '2025-01-01T08:00:00Z',
    updatedAt: '2025-01-15T09:30:00Z',
    createdBy: 'user-1',
  },
  {
    id: 'newsletter-nutricion-mensual',
    name: 'Newsletter de Nutrición Mensual',
    description: 'Newsletter mensual con consejos nutricionales',
    subject: '🥗 Guía de nutrición para este mes',
    templateId: 'template-nutricion',
    htmlContent: '<html><body><h1>Nutrición</h1><p>Contenido personalizado...</p></body></html>',
    schedule: {
      id: 'schedule-2',
      frequency: 'monthly',
      dayOfMonth: 1,
      time: '10:00',
      timezone: 'America/Mexico_City',
      nextScheduledDate: '2025-02-01T10:00:00Z',
      lastSentDate: '2025-01-01T10:00:00Z',
      isActive: true,
    },
    status: 'scheduled',
    tracking: {
      id: 'track-2',
      newsletterId: 'newsletter-nutricion-mensual',
      sentDate: '2025-01-01T10:00:00Z',
      totalRecipients: 245,
      deliveredCount: 240,
      openedCount: 156,
      uniqueOpens: 142,
      clickedCount: 67,
      uniqueClicks: 61,
      unsubscribedCount: 2,
      bouncedCount: 5,
      deliveryRate: 98.0,
      openRate: 63.7,
      clickRate: 27.3,
      clickToOpenRate: 42.9,
      unsubscribeRate: 0.8,
      bounceRate: 2.0,
    },
    totalSent: 1,
    averageOpenRate: 63.7,
    averageClickRate: 27.3,
    createdAt: '2024-12-15T08:00:00Z',
    updatedAt: '2025-01-01T10:30:00Z',
    createdBy: 'user-1',
  },
  {
    id: 'newsletter-draft',
    name: 'Newsletter de Retos - Borrador',
    description: 'Newsletter sobre retos de fitness',
    subject: '💪 Únete al reto de 30 días',
    htmlContent: '<html><body><h1>Retos</h1><p>Contenido en borrador...</p></body></html>',
    status: 'draft',
    totalSent: 0,
    averageOpenRate: 0,
    averageClickRate: 0,
    createdAt: '2025-01-14T08:00:00Z',
    updatedAt: '2025-01-14T08:00:00Z',
    createdBy: 'user-1',
  },
];

export async function fetchNewsletters(): Promise<Newsletter[]> {
  return simulateLatency(newsletters);
}

export async function fetchNewsletterTemplates(): Promise<NewsletterTemplate[]> {
  return simulateLatency(newsletterTemplates);
}

// US-CA-013: Sistema de respuestas automáticas fuera de horario
const afterHoursAutoReplies: AfterHoursAutoReply[] = [
  {
    id: 'after-hours-whatsapp',
    name: 'Respuesta Automática WhatsApp - Horario Laboral',
    description: 'Responde automáticamente a mensajes recibidos fuera del horario de atención en WhatsApp',
    isActive: true,
    businessHours: [
      { id: 'mon', dayOfWeek: 1, dayName: 'Lunes', isEnabled: true, startTime: '09:00', endTime: '18:00' },
      { id: 'tue', dayOfWeek: 2, dayName: 'Martes', isEnabled: true, startTime: '09:00', endTime: '18:00' },
      { id: 'wed', dayOfWeek: 3, dayName: 'Miércoles', isEnabled: true, startTime: '09:00', endTime: '18:00' },
      { id: 'thu', dayOfWeek: 4, dayName: 'Jueves', isEnabled: true, startTime: '09:00', endTime: '18:00' },
      { id: 'fri', dayOfWeek: 5, dayName: 'Viernes', isEnabled: true, startTime: '09:00', endTime: '18:00' },
      { id: 'sat', dayOfWeek: 6, dayName: 'Sábado', isEnabled: false, startTime: '09:00', endTime: '13:00' },
      { id: 'sun', dayOfWeek: 0, dayName: 'Domingo', isEnabled: false, startTime: '09:00', endTime: '13:00' },
    ],
    timezone: 'America/Mexico_City',
    messageTemplate: 'Hola! 👋 Gracias por tu mensaje. Nuestro horario de atención es de lunes a viernes de 9:00 a 18:00. Te responderemos lo antes posible, normalmente en un plazo de 2-4 horas durante nuestro horario laboral. ¡Que tengas un excelente día!',
    channel: 'whatsapp',
    estimatedResponseTime: '2-4 horas (horario laboral)',
    variables: ['{horarioAtencion}', '{tiempoEstimado}'],
    totalRepliesSent: 47,
    lastTriggered: '2025-11-09T20:15:00Z',
    createdAt: '2025-10-01T10:00:00Z',
    updatedAt: '2025-11-08T14:30:00Z',
  },
  {
    id: 'after-hours-email',
    name: 'Respuesta Automática Email - Horario Extendido',
    description: 'Responde automáticamente a emails recibidos fuera del horario de atención',
    isActive: true,
    businessHours: [
      { id: 'mon', dayOfWeek: 1, dayName: 'Lunes', isEnabled: true, startTime: '08:00', endTime: '20:00' },
      { id: 'tue', dayOfWeek: 2, dayName: 'Martes', isEnabled: true, startTime: '08:00', endTime: '20:00' },
      { id: 'wed', dayOfWeek: 3, dayName: 'Miércoles', isEnabled: true, startTime: '08:00', endTime: '20:00' },
      { id: 'thu', dayOfWeek: 4, dayName: 'Jueves', isEnabled: true, startTime: '08:00', endTime: '20:00' },
      { id: 'fri', dayOfWeek: 5, dayName: 'Viernes', isEnabled: true, startTime: '08:00', endTime: '20:00' },
      { id: 'sat', dayOfWeek: 6, dayName: 'Sábado', isEnabled: true, startTime: '10:00', endTime: '14:00' },
      { id: 'sun', dayOfWeek: 0, dayName: 'Domingo', isEnabled: false, startTime: '10:00', endTime: '14:00' },
    ],
    timezone: 'America/Mexico_City',
    messageTemplate: 'Hola,\n\nGracias por contactarnos. Hemos recibido tu mensaje fuera de nuestro horario de atención.\n\nHorario de atención:\n- Lunes a Viernes: 8:00 - 20:00\n- Sábados: 10:00 - 14:00\n- Domingos: Cerrado\n\nTe responderemos mañana a primera hora (9:00 AM). Si es urgente, puedes contactarnos por WhatsApp.\n\nSaludos,\nTu entrenador personal',
    channel: 'email',
    estimatedResponseTime: 'Mañana a las 9:00 AM',
    variables: ['{horarioAtencion}', '{tiempoEstimado}'],
    totalRepliesSent: 23,
    lastTriggered: '2025-11-09T21:30:00Z',
    createdAt: '2025-10-05T10:00:00Z',
    updatedAt: '2025-11-07T11:20:00Z',
  },
];

// US-CA-014: Sistema de campañas promocionales
const promotionalCampaigns: PromotionalCampaign[] = [
  {
    id: 'promo-black-friday-2025',
    name: 'Black Friday 2025 - Descuento 30%',
    description: 'Campaña promocional de Black Friday con descuento del 30% en todos los planes',
    messageTemplate: '¡Hola {nombre}! 🎉 Black Friday está aquí. Obtén un 30% de descuento en todos nuestros planes. Válido hasta el 30 de noviembre. ¡No te lo pierdas! Usa el código: BLACK30',
    channel: 'whatsapp',
    recipients: {
      type: 'all',
    },
    variables: ['{nombre}', '{descuento}', '{codigo}', '{fechaVencimiento}'],
    status: 'completed',
    sentDate: '2025-11-25T09:00:00Z',
    tracking: {
      id: 'track-promo-bf',
      campaignId: 'promo-black-friday-2025',
      sentDate: '2025-11-25T09:00:00Z',
      totalRecipients: 245,
      sentCount: 245,
      deliveredCount: 238,
      openedCount: 189,
      clickedCount: 67,
      repliedCount: 45,
      conversionCount: 32,
      revenueGenerated: 12800,
      deliveryRate: 97.1,
      openRate: 77.2,
      clickRate: 27.3,
      replyRate: 18.4,
      conversionRate: 13.1,
    },
    createdAt: '2025-11-20T10:00:00Z',
    updatedAt: '2025-11-30T18:00:00Z',
    createdBy: 'user-1',
  },
  {
    id: 'promo-verano-inactivos',
    name: 'Promoción Verano - Reactivación Clientes Inactivos',
    description: 'Oferta especial de verano para reactivar clientes inactivos con descuento del 25%',
    messageTemplate: '¡Hola {nombre}! ☀️ El verano está aquí y queremos verte de vuelta. Oferta especial: 25% de descuento en tu próximo plan. Válido hasta el 15 de agosto. ¡Es momento de retomar tu rutina!',
    channel: 'email',
    recipients: {
      type: 'inactive-clients',
    },
    variables: ['{nombre}', '{descuento}', '{fechaVencimiento}'],
    status: 'scheduled',
    scheduledDate: '2025-07-01T10:00:00Z',
    createdAt: '2025-06-25T10:00:00Z',
    updatedAt: '2025-06-28T14:30:00Z',
    createdBy: 'user-1',
  },
  {
    id: 'promo-bono-trimestral',
    name: 'Promoción Bono Trimestral - Segmento Premium',
    description: 'Oferta de bono trimestral con sesión extra gratis para clientes premium',
    messageTemplate: '¡Hola {nombre}! 💎 Como cliente Premium, tenemos una oferta especial para ti: Contrata un bono trimestral y recibe 1 sesión adicional GRATIS. Oferta válida hasta el {fechaVencimiento}. ¡Aprovecha ahora!',
    channel: 'whatsapp',
    recipients: {
      type: 'segment',
      segmentId: 'seg-premium',
      segmentName: 'Clientes Premium',
    },
    variables: ['{nombre}', '{oferta}', '{fechaVencimiento}'],
    status: 'running',
    sentDate: '2025-11-10T09:00:00Z',
    tracking: {
      id: 'track-promo-bono',
      campaignId: 'promo-bono-trimestral',
      sentDate: '2025-11-10T09:00:00Z',
      totalRecipients: 42,
      sentCount: 42,
      deliveredCount: 41,
      openedCount: 38,
      clickedCount: 24,
      repliedCount: 18,
      conversionCount: 12,
      revenueGenerated: 4800,
      deliveryRate: 97.6,
      openRate: 90.5,
      clickRate: 57.1,
      replyRate: 42.9,
      conversionRate: 28.6,
    },
    createdAt: '2025-11-05T10:00:00Z',
    updatedAt: '2025-11-10T09:30:00Z',
    createdBy: 'user-1',
  },
  {
    id: 'promo-clase-grupal',
    name: 'Invitación Clase Grupal - Todos los Clientes',
    description: 'Invitación a clase grupal especial de fin de mes para todos los clientes',
    messageTemplate: '¡Hola {nombre}! 👥 Te invitamos a nuestra clase grupal especial este sábado a las 10:00 AM. Es GRATIS para todos nuestros clientes. ¡Ven con un amigo y ambos recibirán un descuento del 15%! Confirma tu asistencia respondiendo a este mensaje.',
    channel: 'whatsapp',
    recipients: {
      type: 'all',
    },
    variables: ['{nombre}', '{fechaClase}', '{horaClase}', '{descuento}'],
    status: 'draft',
    createdAt: '2025-11-08T10:00:00Z',
    updatedAt: '2025-11-08T10:00:00Z',
    createdBy: 'user-1',
  },
];

export async function fetchAfterHoursAutoReplies(): Promise<AfterHoursAutoReply[]> {
  return simulateLatency(afterHoursAutoReplies);
}

export async function fetchPromotionalCampaigns(): Promise<PromotionalCampaign[]> {
  return simulateLatency(promotionalCampaigns);
}

// US-CA-015: Integración con sistema de reservas
const reservationsIntegrationData: ReservationsIntegration = {
  isEnabled: true,
  rules: [
    {
      id: 'rule-new-session-reminder',
      name: 'Recordatorio nueva sesión',
      description: 'Envía recordatorio automático 24 horas antes de cada nueva sesión reservada',
      eventType: 'new-session',
      automationType: 'reminder',
      triggerDelay: {
        type: 'before',
        hours: 24,
      },
      messageTemplate: '¡Hola {nombre}! Te recordamos que tienes una sesión mañana {fecha} a las {hora}. ¡Nos vemos pronto!',
      channel: 'whatsapp',
      isActive: true,
      totalTriggered: 156,
      lastTriggered: '2025-11-30T14:30:00Z',
      createdAt: '2025-10-01T10:00:00Z',
      updatedAt: '2025-11-15T09:00:00Z',
    },
    {
      id: 'rule-cancellation-followup',
      name: 'Seguimiento cancelación',
      description: 'Envía mensaje de seguimiento cuando se cancela una sesión para ofrecer reagendar',
      eventType: 'session-cancelled',
      automationType: 'cancellation-follow-up',
      triggerDelay: {
        type: 'after',
        hours: 2,
      },
      messageTemplate: 'Hola {nombre}, vemos que cancelaste tu sesión del {fecha}. ¿Te gustaría reagendarla? Estamos aquí para ayudarte.',
      channel: 'whatsapp',
      isActive: true,
      totalTriggered: 23,
      lastTriggered: '2025-11-29T16:45:00Z',
      createdAt: '2025-10-01T10:00:00Z',
      updatedAt: '2025-11-10T11:00:00Z',
    },
    {
      id: 'rule-no-show-followup',
      name: 'Seguimiento ausencia sin avisar',
      description: 'Envía mensaje de seguimiento cuando un cliente no asiste a una sesión sin avisar',
      eventType: 'no-show',
      automationType: 'follow-up',
      triggerDelay: {
        type: 'after',
        hours: 1,
      },
      messageTemplate: 'Hola {nombre}, notamos que no pudiste asistir a tu sesión de hoy. ¿Todo bien? Estamos aquí para ayudarte a reagendar.',
      channel: 'whatsapp',
      isActive: true,
      totalTriggered: 8,
      lastTriggered: '2025-11-28T10:15:00Z',
      createdAt: '2025-10-01T10:00:00Z',
      updatedAt: '2025-11-05T09:00:00Z',
    },
    {
      id: 'rule-session-confirmation',
      name: 'Confirmación de sesión',
      description: 'Envía confirmación inmediata cuando se crea una nueva reserva',
      eventType: 'new-session',
      automationType: 'confirmation',
      messageTemplate: '¡Hola {nombre}! Tu sesión ha sido confirmada para el {fecha} a las {hora}. ¡Te esperamos!',
      channel: 'email',
      isActive: true,
      totalTriggered: 89,
      lastTriggered: '2025-11-30T18:20:00Z',
      createdAt: '2025-10-15T10:00:00Z',
      updatedAt: '2025-11-20T10:00:00Z',
    },
  ],
  recentEvents: [
    {
      id: 'event-1',
      reservationId: 'res-123',
      clientId: 'client-456',
      clientName: 'María González',
      eventType: 'new-session',
      sessionDate: '2025-12-02',
      sessionTime: '10:00',
      createdAt: '2025-11-30T18:20:00Z',
    },
    {
      id: 'event-2',
      reservationId: 'res-124',
      clientId: 'client-789',
      clientName: 'Juan Pérez',
      eventType: 'session-cancelled',
      sessionDate: '2025-12-01',
      sessionTime: '16:00',
      createdAt: '2025-11-30T14:30:00Z',
    },
    {
      id: 'event-3',
      reservationId: 'res-125',
      clientId: 'client-321',
      clientName: 'Ana Martínez',
      eventType: 'session-rescheduled',
      sessionDate: '2025-12-03',
      sessionTime: '11:00',
      originalDate: '2025-12-02',
      originalTime: '11:00',
      createdAt: '2025-11-30T12:15:00Z',
    },
  ],
  totalEventsProcessed: 276,
  eventsLast24h: 12,
  lastSyncDate: '2025-11-30T18:30:00Z',
  syncStatus: 'synced',
};

export async function fetchReservationsIntegration(): Promise<ReservationsIntegration> {
  return simulateLatency(reservationsIntegrationData);
}

// US-CA-016: Panel centralizado de automatizaciones
const centralAutomationsPanelData: CentralAutomationsPanel = {
  automations: [
    {
      id: 'auto-session-reminders',
      name: 'Recordatorios de Sesión',
      type: 'session-reminder',
      typeLabel: 'Recordatorios de sesión',
      description: 'Recordatorios automáticos 24h y 2h antes de cada sesión',
      status: 'active',
      nextScheduledSend: '2025-12-01T08:00:00Z',
      lastScheduledSend: '2025-11-30T08:00:00Z',
      totalSends: 1247,
      activeRecipients: 42,
      successRate: 94.5,
      createdAt: '2025-10-01T10:00:00Z',
      updatedAt: '2025-11-30T18:00:00Z',
      canPause: true,
      canResume: false,
      canEdit: true,
      canDelete: false,
    },
    {
      id: 'auto-welcome-sequence',
      name: 'Secuencia de Bienvenida',
      type: 'welcome-sequence',
      typeLabel: 'Secuencia de bienvenida',
      description: 'Secuencia de 3 mensajes para nuevos clientes',
      status: 'active',
      nextScheduledSend: '2025-12-01T09:00:00Z',
      lastScheduledSend: '2025-11-30T09:00:00Z',
      totalSends: 89,
      activeRecipients: 12,
      successRate: 87.2,
      createdAt: '2025-10-05T10:00:00Z',
      updatedAt: '2025-11-28T10:00:00Z',
      canPause: true,
      canResume: false,
      canEdit: true,
      canDelete: false,
    },
    {
      id: 'auto-absence-followup',
      name: 'Seguimiento de Ausencias',
      type: 'absence-follow-up',
      typeLabel: 'Seguimiento de ausencias',
      description: 'Mensajes automáticos cuando un cliente falta sin avisar',
      status: 'active',
      nextScheduledSend: undefined,
      lastScheduledSend: '2025-11-28T10:15:00Z',
      totalSends: 23,
      activeRecipients: 0,
      successRate: 78.3,
      createdAt: '2025-10-10T10:00:00Z',
      updatedAt: '2025-11-28T10:15:00Z',
      canPause: true,
      canResume: false,
      canEdit: true,
      canDelete: false,
    },
    {
      id: 'auto-payment-reminders',
      name: 'Recordatorios de Pago',
      type: 'payment-reminder',
      typeLabel: 'Recordatorios de pago',
      description: 'Recordatorios automáticos para pagos pendientes',
      status: 'paused',
      nextScheduledSend: undefined,
      lastScheduledSend: '2025-11-25T09:00:00Z',
      totalSends: 156,
      activeRecipients: 8,
      successRate: 82.1,
      createdAt: '2025-09-15T10:00:00Z',
      updatedAt: '2025-11-25T14:00:00Z',
      canPause: false,
      canResume: true,
      canEdit: true,
      canDelete: false,
    },
    {
      id: 'auto-inactivity-sequence',
      name: 'Secuencia de Inactividad',
      type: 'inactivity-sequence',
      typeLabel: 'Secuencia de inactividad',
      description: 'Secuencia para reactivar clientes inactivos',
      status: 'active',
      nextScheduledSend: '2025-12-02T10:00:00Z',
      lastScheduledSend: '2025-11-29T10:00:00Z',
      totalSends: 45,
      activeRecipients: 15,
      successRate: 65.4,
      createdAt: '2025-10-20T10:00:00Z',
      updatedAt: '2025-11-29T10:00:00Z',
      canPause: true,
      canResume: false,
      canEdit: true,
      canDelete: false,
    },
    {
      id: 'auto-important-dates',
      name: 'Fechas Importantes',
      type: 'important-date',
      typeLabel: 'Fechas importantes',
      description: 'Mensajes automáticos para cumpleaños y aniversarios',
      status: 'active',
      nextScheduledSend: '2025-12-05T09:00:00Z',
      lastScheduledSend: '2025-11-28T09:00:00Z',
      totalSends: 34,
      activeRecipients: 5,
      successRate: 91.2,
      createdAt: '2025-09-01T10:00:00Z',
      updatedAt: '2025-11-28T09:00:00Z',
      canPause: true,
      canResume: false,
      canEdit: true,
      canDelete: false,
    },
    {
      id: 'auto-reservation-integration',
      name: 'Integración con Reservas',
      type: 'reservation-integration',
      typeLabel: 'Integración con reservas',
      description: 'Automatizaciones basadas en eventos del calendario de reservas',
      status: 'active',
      nextScheduledSend: undefined,
      lastScheduledSend: '2025-11-30T18:20:00Z',
      totalSends: 276,
      activeRecipients: 0,
      successRate: 88.5,
      createdAt: '2025-10-01T10:00:00Z',
      updatedAt: '2025-11-30T18:30:00Z',
      canPause: true,
      canResume: false,
      canEdit: true,
      canDelete: false,
    },
  ],
  totalActive: 6,
  totalPaused: 1,
  totalFinished: 0,
  upcomingSends: [
    {
      automationId: 'auto-session-reminders',
      automationName: 'Recordatorios de Sesión',
      scheduledDate: '2025-12-01T08:00:00Z',
      recipientCount: 12,
      channel: 'whatsapp',
    },
    {
      automationId: 'auto-welcome-sequence',
      automationName: 'Secuencia de Bienvenida',
      scheduledDate: '2025-12-01T09:00:00Z',
      recipientCount: 3,
      channel: 'email',
    },
    {
      automationId: 'auto-inactivity-sequence',
      automationName: 'Secuencia de Inactividad',
      scheduledDate: '2025-12-02T10:00:00Z',
      recipientCount: 5,
      channel: 'whatsapp',
    },
    {
      automationId: 'auto-important-dates',
      automationName: 'Fechas Importantes',
      scheduledDate: '2025-12-05T09:00:00Z',
      recipientCount: 2,
      channel: 'email',
    },
  ],
  lastUpdated: '2025-11-30T18:30:00Z',
};

export async function fetchCentralAutomationsPanel(): Promise<CentralAutomationsPanel> {
  return simulateLatency(centralAutomationsPanelData);
}

// US-CA-017: Sistema de alertas de mensajes importantes
const messageAlertsDashboardData: MessageAlertsDashboard = {
  activeAlerts: [
    {
      id: 'alert-001',
      messageId: 'msg-001',
      messageType: 'recordatorio-pago',
      messageTypeLabel: 'Recordatorio de Pago',
      clientId: 'client-001',
      clientName: 'María González',
      channel: 'whatsapp',
      sentAt: '2025-11-09T08:00:00Z',
      timeSinceSent: {
        hours: 26,
        days: 1,
      },
      threshold: {
        type: 'replied',
        hours: 24,
      },
      priority: 'high',
      status: 'active',
      messageContent: 'Hola María! 👋 Te recordamos que tienes un pago pendiente de €120 con vencimiento el 10/11/2025. Puedes pagar aquí: [link]. ¡Gracias!',
      createdAt: '2025-11-10T08:00:00Z',
      updatedAt: '2025-11-10T08:00:00Z',
    },
    {
      id: 'alert-002',
      messageId: 'msg-002',
      messageType: 'recordatorio-sesion',
      messageTypeLabel: 'Recordatorio de Sesión',
      clientId: 'client-002',
      clientName: 'Juan Pérez',
      channel: 'email',
      sentAt: '2025-11-08T10:00:00Z',
      timeSinceSent: {
        hours: 50,
        days: 2,
      },
      threshold: {
        type: 'opened',
        hours: 48,
      },
      priority: 'urgent',
      status: 'active',
      messageContent: 'Hola Juan, recordatorio: sesión mañana a las 18:00. Lugar: Gimnasio Central.',
      messageSubject: 'Recordatorio de sesión - 10 de noviembre',
      createdAt: '2025-11-10T10:00:00Z',
      updatedAt: '2025-11-10T10:00:00Z',
    },
    {
      id: 'alert-003',
      messageId: 'msg-003',
      messageType: 'seguimiento',
      messageTypeLabel: 'Seguimiento',
      clientId: 'client-003',
      clientName: 'Ana Martínez',
      channel: 'whatsapp',
      sentAt: '2025-11-09T14:00:00Z',
      timeSinceSent: {
        hours: 18,
        days: 0,
      },
      threshold: {
        type: 'replied',
        hours: 12,
      },
      priority: 'medium',
      status: 'acknowledged',
      messageContent: 'Hola Ana! 👋 ¿Cómo te sientes con tu entrenamiento? ¿Hay algo en lo que podamos ayudarte?',
      acknowledgedAt: '2025-11-10T09:00:00Z',
      createdAt: '2025-11-09T14:00:00Z',
      updatedAt: '2025-11-10T09:00:00Z',
    },
  ],
  totalActive: 2,
  byPriority: {
    urgent: 1,
    high: 1,
    medium: 0,
    low: 0,
  },
  byStatus: {
    active: 2,
    acknowledged: 1,
    resolved: 0,
    dismissed: 0,
  },
  settings: [
    {
      id: 'settings-recordatorio-pago',
      messageType: 'recordatorio-pago',
      messageTypeLabel: 'Recordatorio de Pago',
      isEnabled: true,
      thresholds: {
        opened: {
          enabled: false,
          hours: 48,
          priority: 'medium',
        },
        replied: {
          enabled: true,
          hours: 24,
          priority: 'high',
        },
      },
      notificationChannels: ['email', 'in-app'],
      autoEscalation: {
        enabled: true,
        escalateAfterHours: 48,
      },
      createdAt: '2025-10-01T10:00:00Z',
      updatedAt: '2025-11-01T10:00:00Z',
    },
    {
      id: 'settings-recordatorio-sesion',
      messageType: 'recordatorio-sesion',
      messageTypeLabel: 'Recordatorio de Sesión',
      isEnabled: true,
      thresholds: {
        opened: {
          enabled: true,
          hours: 48,
          priority: 'urgent',
        },
        replied: {
          enabled: false,
          hours: 24,
          priority: 'medium',
        },
      },
      notificationChannels: ['email', 'push', 'in-app'],
      autoEscalation: {
        enabled: true,
        escalateAfterHours: 72,
      },
      createdAt: '2025-10-01T10:00:00Z',
      updatedAt: '2025-11-01T10:00:00Z',
    },
  ],
  lastUpdated: '2025-11-10T10:00:00Z',
};

// US-CA-018: Sistema de horarios preferidos de envío
const preferredSendingSchedulesDashboardData: PreferredSendingSchedulesDashboard = {
  clientSchedules: [
    {
      id: 'client-schedule-001',
      clientId: 'client-001',
      clientName: 'María González',
      timezone: 'Europe/Madrid',
      windows: [
        { id: 'w1', dayOfWeek: 1, dayName: 'Lunes', isEnabled: true, startTime: '09:00', endTime: '12:00' },
        { id: 'w2', dayOfWeek: 2, dayName: 'Martes', isEnabled: true, startTime: '09:00', endTime: '12:00' },
        { id: 'w3', dayOfWeek: 3, dayName: 'Miércoles', isEnabled: true, startTime: '09:00', endTime: '12:00' },
        { id: 'w4', dayOfWeek: 4, dayName: 'Jueves', isEnabled: true, startTime: '09:00', endTime: '12:00' },
        { id: 'w5', dayOfWeek: 5, dayName: 'Viernes', isEnabled: true, startTime: '09:00', endTime: '12:00' },
      ],
      isActive: true,
      appliesTo: {
        channels: ['whatsapp', 'email'],
        messageTypes: ['recordatorio-sesion', 'seguimiento', 'recordatorio-pago'],
      },
      createdAt: '2025-10-15T10:00:00Z',
      updatedAt: '2025-11-01T10:00:00Z',
    },
    {
      id: 'client-schedule-002',
      clientId: 'client-002',
      clientName: 'Juan Pérez',
      timezone: 'Europe/Madrid',
      windows: [
        { id: 'w1', dayOfWeek: 1, dayName: 'Lunes', isEnabled: true, startTime: '18:00', endTime: '20:00' },
        { id: 'w2', dayOfWeek: 2, dayName: 'Martes', isEnabled: true, startTime: '18:00', endTime: '20:00' },
        { id: 'w3', dayOfWeek: 3, dayName: 'Miércoles', isEnabled: true, startTime: '18:00', endTime: '20:00' },
        { id: 'w4', dayOfWeek: 4, dayName: 'Jueves', isEnabled: true, startTime: '18:00', endTime: '20:00' },
        { id: 'w5', dayOfWeek: 5, dayName: 'Viernes', isEnabled: true, startTime: '18:00', endTime: '20:00' },
      ],
      isActive: true,
      appliesTo: {
        channels: ['whatsapp', 'sms'],
        messageTypes: ['recordatorio-sesion', 'seguimiento'],
      },
      createdAt: '2025-10-20T10:00:00Z',
      updatedAt: '2025-11-05T10:00:00Z',
    },
  ],
  groupSchedules: [
    {
      id: 'group-schedule-001',
      groupId: 'group-premium',
      groupName: 'Clientes Premium',
      timezone: 'Europe/Madrid',
      windows: [
        { id: 'w1', dayOfWeek: 1, dayName: 'Lunes', isEnabled: true, startTime: '10:00', endTime: '13:00' },
        { id: 'w2', dayOfWeek: 2, dayName: 'Martes', isEnabled: true, startTime: '10:00', endTime: '13:00' },
        { id: 'w3', dayOfWeek: 3, dayName: 'Miércoles', isEnabled: true, startTime: '10:00', endTime: '13:00' },
        { id: 'w4', dayOfWeek: 4, dayName: 'Jueves', isEnabled: true, startTime: '10:00', endTime: '13:00' },
        { id: 'w5', dayOfWeek: 5, dayName: 'Viernes', isEnabled: true, startTime: '10:00', endTime: '13:00' },
      ],
      isActive: true,
      appliesTo: {
        channels: ['whatsapp', 'email'],
        messageTypes: ['recordatorio-sesion', 'seguimiento', 'fecha-importante'],
      },
      clientCount: 42,
      createdAt: '2025-09-15T10:00:00Z',
      updatedAt: '2025-11-01T10:00:00Z',
    },
  ],
  rules: [
    {
      id: 'rule-default-business-hours',
      name: 'Horario Laboral Estándar',
      description: 'Horario preferido para todos los clientes: lunes a viernes de 9:00 a 18:00',
      priority: 1,
      appliesTo: {
        type: 'all',
      },
      schedule: {
        timezone: 'Europe/Madrid',
        windows: [
          { id: 'w1', dayOfWeek: 1, dayName: 'Lunes', isEnabled: true, startTime: '09:00', endTime: '18:00' },
          { id: 'w2', dayOfWeek: 2, dayName: 'Martes', isEnabled: true, startTime: '09:00', endTime: '18:00' },
          { id: 'w3', dayOfWeek: 3, dayName: 'Miércoles', isEnabled: true, startTime: '09:00', endTime: '18:00' },
          { id: 'w4', dayOfWeek: 4, dayName: 'Jueves', isEnabled: true, startTime: '09:00', endTime: '18:00' },
          { id: 'w5', dayOfWeek: 5, dayName: 'Viernes', isEnabled: true, startTime: '09:00', endTime: '18:00' },
        ],
      },
      channels: ['whatsapp', 'email', 'sms'],
      messageTypes: ['recordatorio-sesion', 'seguimiento', 'recordatorio-pago', 'bienvenida'],
      isActive: true,
      createdAt: '2025-09-01T10:00:00Z',
      updatedAt: '2025-11-01T10:00:00Z',
    },
  ],
  totalClientsWithSchedule: 2,
  totalGroupsWithSchedule: 1,
  totalRules: 1,
  nextScheduledMessages: [
    {
      messageId: 'msg-scheduled-001',
      messageType: 'recordatorio-sesion',
      clientId: 'client-001',
      clientName: 'María González',
      scheduledTime: '2025-11-11T10:00:00Z',
      preferredWindow: {
        startTime: '09:00',
        endTime: '12:00',
      },
      channel: 'whatsapp',
    },
    {
      messageId: 'msg-scheduled-002',
      messageType: 'seguimiento',
      clientId: 'client-002',
      clientName: 'Juan Pérez',
      scheduledTime: '2025-11-11T19:00:00Z',
      preferredWindow: {
        startTime: '18:00',
        endTime: '20:00',
      },
      channel: 'whatsapp',
    },
  ],
  lastUpdated: '2025-11-10T10:00:00Z',
};

export async function fetchMessageAlertsDashboard(): Promise<MessageAlertsDashboard> {
  return simulateLatency(messageAlertsDashboardData);
}

export async function fetchPreferredSendingSchedulesDashboard(): Promise<PreferredSendingSchedulesDashboard> {
  return simulateLatency(preferredSendingSchedulesDashboardData);
}

// US-CA-019: Multi-step sequences with conditional logic
const multiStepSequencesData: MultiStepSequence[] = [
  {
    id: 'seq-onboarding-completo',
    name: 'Onboarding Completo con Lógica Condicional',
    description: 'Secuencia de onboarding que se adapta según las respuestas del cliente',
    trigger: 'new-client',
    steps: [
      {
        id: 'step-1',
        stepNumber: 1,
        name: 'Bienvenida Inicial',
        description: 'Mensaje de bienvenida al nuevo cliente',
        messageTemplate: '¡Hola {nombre}! Bienvenido/a. Estamos emocionados de comenzar este viaje contigo.',
        channel: 'whatsapp',
        delay: { value: 0, unit: 'minutes' },
        variables: ['nombre'],
        pauseOnResponse: true,
        pauseOnAction: false,
        isActive: true,
      },
      {
        id: 'step-2',
        stepNumber: 2,
        name: 'Información sobre el Programa',
        description: 'Información sobre qué esperar',
        messageTemplate: 'En los próximos días te enviaremos información sobre tu programa personalizado. ¿Tienes alguna pregunta específica?',
        channel: 'email',
        delay: { value: 1, unit: 'days' },
        variables: ['nombre'],
        conditionalRules: [
          {
            id: 'rule-1',
            condition: {
              type: 'response',
              field: 'response',
              operator: 'contains',
              value: 'pregunta',
            },
            thenAction: {
              type: 'send-message',
              messageId: 'msg-preguntas',
            },
          },
        ],
        pauseOnResponse: true,
        pauseOnAction: false,
        isActive: true,
      },
      {
        id: 'step-3',
        stepNumber: 3,
        name: 'Preparación Primera Sesión',
        description: 'Preparación para la primera sesión',
        messageTemplate: 'Tu primera sesión está programada para {fecha}. ¿Necesitas alguna recomendación previa?',
        channel: 'whatsapp',
        delay: { value: 2, unit: 'days' },
        scheduledTime: '09:00',
        variables: ['nombre', 'fecha'],
        pauseOnResponse: true,
        pauseOnAction: true,
        isActive: true,
      },
    ],
    activeClients: 12,
    pausedClients: 3,
    completionRate: 75.5,
    averageCompletionTime: 4.2,
    responseRate: 68.3,
    status: 'running',
    createdAt: '2025-10-15T10:00:00Z',
    updatedAt: '2025-11-01T10:00:00Z',
    createdBy: 'user-001',
  },
  {
    id: 'seq-reactivacion-inteligente',
    name: 'Reactivación Inteligente',
    description: 'Secuencia que se adapta según el nivel de inactividad',
    trigger: 'inactivity',
    triggerCondition: {
      type: 'daysSinceLastSession',
      value: 30,
    },
    steps: [
      {
        id: 'step-reactivacion-1',
        stepNumber: 1,
        name: 'Check-in Amigable',
        messageTemplate: 'Hola {nombre}, hace {dias} días que no nos vemos. ¿Todo bien?',
        channel: 'whatsapp',
        delay: { value: 0, unit: 'hours' },
        variables: ['nombre', 'dias'],
        pauseOnResponse: true,
        pauseOnAction: true,
        isActive: true,
      },
      {
        id: 'step-reactivacion-2',
        stepNumber: 2,
        name: 'Oferta Especial',
        messageTemplate: 'Tenemos una oferta especial para ti. ¿Te interesa retomar tus entrenamientos?',
        channel: 'email',
        delay: { value: 3, unit: 'days' },
        conditionalRules: [
          {
            id: 'rule-reactivacion-1',
            condition: {
              type: 'response',
              operator: 'contains',
              value: 'sí',
            },
            thenAction: {
              type: 'jump-to-step',
              stepId: 'step-reactivacion-3',
            },
          },
        ],
        pauseOnResponse: true,
        pauseOnAction: true,
        isActive: true,
      },
      {
        id: 'step-reactivacion-3',
        stepNumber: 3,
        name: 'Seguimiento de Interés',
        messageTemplate: 'Perfecto, te ayudo a agendar tu próxima sesión. ¿Qué día te viene bien?',
        channel: 'whatsapp',
        delay: { value: 1, unit: 'days' },
        variables: ['nombre'],
        pauseOnResponse: true,
        pauseOnAction: true,
        isActive: true,
      },
    ],
    activeClients: 8,
    pausedClients: 2,
    completionRate: 62.5,
    averageCompletionTime: 6.8,
    responseRate: 55.2,
    status: 'running',
    createdAt: '2025-09-20T10:00:00Z',
    updatedAt: '2025-11-01T10:00:00Z',
    createdBy: 'user-001',
  },
];

export async function fetchMultiStepSequences(): Promise<MultiStepSequence[]> {
  return simulateLatency(multiStepSequencesData);
}

// US-CA-020: Export reports
const exportReportsData: ExportReport[] = [
  {
    id: 'report-001',
    configuration: {
      name: 'Reporte Mensual de Comunicación - Octubre 2025',
      format: 'pdf',
      period: 'monthly',
      includeMetrics: {
        communicationMetrics: true,
        periodComparison: true,
        automationEffectiveness: true,
        channelBreakdown: true,
        messageTypeBreakdown: true,
        dailyTrends: true,
        topPerformers: true,
      },
      compareWithPreviousPeriod: true,
      includeCharts: true,
      includeRawData: false,
    },
    generatedAt: '2025-11-01T10:00:00Z',
    generatedBy: 'user-001',
    fileUrl: '/reports/report-001.pdf',
    fileSize: 2456789,
    status: 'completed',
    metrics: {
      totalMessagesSent: 1247,
      totalMessagesDelivered: 1205,
      totalMessagesOpened: 856,
      totalMessagesReplied: 423,
      deliveryRate: 96.6,
      openRate: 71.0,
      replyRate: 35.1,
      byChannel: [
        {
          channel: 'whatsapp',
          sent: 856,
          delivered: 845,
          opened: 712,
          replied: 389,
          deliveryRate: 98.7,
          openRate: 84.3,
          replyRate: 46.0,
        },
        {
          channel: 'email',
          sent: 312,
          delivered: 289,
          opened: 112,
          replied: 28,
          deliveryRate: 92.6,
          openRate: 38.8,
          replyRate: 9.7,
        },
        {
          channel: 'sms',
          sent: 79,
          delivered: 71,
          opened: 32,
          replied: 6,
          deliveryRate: 89.9,
          openRate: 45.1,
          replyRate: 8.5,
        },
      ],
      byMessageType: [
        {
          messageType: 'recordatorio-sesion',
          messageTypeLabel: 'Recordatorios de Sesión',
          sent: 456,
          opened: 389,
          replied: 156,
          openRate: 85.3,
          replyRate: 34.2,
        },
        {
          messageType: 'bienvenida',
          messageTypeLabel: 'Bienvenida',
          sent: 234,
          opened: 198,
          replied: 89,
          openRate: 84.6,
          replyRate: 38.0,
        },
      ],
      byDay: [],
    },
    periodComparison: {
      current: {
        totalMessagesSent: 1247,
        totalMessagesDelivered: 1205,
        totalMessagesOpened: 856,
        totalMessagesReplied: 423,
        deliveryRate: 96.6,
        openRate: 71.0,
        replyRate: 35.1,
        byChannel: [],
        byMessageType: [],
        byDay: [],
      },
      previous: {
        totalMessagesSent: 1089,
        totalMessagesDelivered: 1056,
        totalMessagesOpened: 712,
        totalMessagesReplied: 345,
        deliveryRate: 97.0,
        openRate: 67.4,
        replyRate: 31.7,
        byChannel: [],
        byMessageType: [],
        byDay: [],
      },
      changes: [
        {
          metric: 'Mensajes Enviados',
          currentValue: 1247,
          previousValue: 1089,
          change: 158,
          changePercentage: 14.5,
          trend: 'up',
        },
        {
          metric: 'Tasa de Apertura',
          currentValue: 71.0,
          previousValue: 67.4,
          change: 3.6,
          changePercentage: 5.3,
          trend: 'up',
        },
        {
          metric: 'Tasa de Respuesta',
          currentValue: 35.1,
          previousValue: 31.7,
          change: 3.4,
          changePercentage: 10.7,
          trend: 'up',
        },
      ],
    },
    automationEffectiveness: [
      {
        automationId: 'auto-001',
        automationName: 'Recordatorios de Sesión',
        automationType: 'session-reminder',
        automationTypeLabel: 'Recordatorios de Sesión',
        totalSent: 456,
        totalDelivered: 445,
        totalOpened: 389,
        totalReplied: 156,
        deliveryRate: 97.6,
        openRate: 85.3,
        replyRate: 34.2,
        trend: 'up',
        changePercentage: 8.5,
      },
      {
        automationId: 'auto-002',
        automationName: 'Secuencia de Bienvenida',
        automationType: 'welcome-sequence',
        automationTypeLabel: 'Secuencias de Bienvenida',
        totalSent: 234,
        totalDelivered: 228,
        totalOpened: 198,
        totalReplied: 89,
        deliveryRate: 97.4,
        openRate: 84.6,
        replyRate: 38.0,
        conversionRate: 72.5,
        trend: 'up',
        changePercentage: 12.3,
      },
    ],
  },
  {
    id: 'report-002',
    configuration: {
      name: 'Análisis de Efectividad - Últimos 30 días',
      format: 'excel',
      period: '30d',
      includeMetrics: {
        communicationMetrics: true,
        periodComparison: false,
        automationEffectiveness: true,
        channelBreakdown: true,
        messageTypeBreakdown: true,
        dailyTrends: true,
        topPerformers: true,
      },
      compareWithPreviousPeriod: false,
      includeCharts: false,
      includeRawData: true,
    },
    generatedAt: '2025-11-05T14:30:00Z',
    generatedBy: 'user-001',
    fileUrl: '/reports/report-002.xlsx',
    fileSize: 1234567,
    status: 'completed',
  },
];

export async function fetchExportReports(): Promise<ExportReport[]> {
  return simulateLatency(exportReportsData);
}

export async function fetchMissionControlSnapshot(): Promise<MissionControlSnapshot> {
  const [
    summary,
    campaigns,
    emails,
    sequences,
    automations,
    health,
    roadmapItems,
    reminderTemplates,
    clientSettings,
    reminders,
    welcomeSeqs,
    absenceAutos,
    messageTemplates,
    scheduledMsgs,
    inactivityAutos,
    importantDateAutos,
    paymentReminderAutos,
    messageStats,
    clientSegs,
    bulkMsgs,
    newslettersData,
    newsletterTemps,
    afterHoursReplies,
    promotionalCamps,
    messageAlertsDashboard,
    preferredSendingSchedulesDashboard,
    multiStepSeqs,
    exportReps,
  ] = await Promise.all([
    fetchMissionControlSummary(),
    fetchMultiChannelCampaigns(),
    fetchEmailPrograms(),
    fetchLifecycleSequences(),
    fetchMessagingAutomations(),
    fetchChannelHealthMetrics(),
    fetchAutomationRoadmap(),
    fetchSessionReminderTemplates(),
    fetchClientReminderSettings(),
    fetchUpcomingReminders(),
    fetchWelcomeSequences(),
    fetchAbsenceAutomations(),
    fetchMessageTemplates(),
    fetchScheduledMessages(),
    fetchInactivityAutomations(),
    fetchImportantDateAutomations(),
    fetchPaymentReminderAutomations(),
    fetchMessageStatisticsDashboard(),
    fetchClientSegments(),
    fetchBulkMessages(),
    fetchNewsletters(),
    fetchNewsletterTemplates(),
    fetchAfterHoursAutoReplies(),
    fetchPromotionalCampaigns(),
    fetchReservationsIntegration(),
    fetchCentralAutomationsPanel(),
    fetchMessageAlertsDashboard(),
    fetchPreferredSendingSchedulesDashboard(),
    fetchMultiStepSequences(),
    fetchExportReports(),
  ]);

  return {
    summary,
    campaigns,
    emailPrograms: emails,
    lifecycleSequences: sequences,
    messagingAutomations: automations,
    channelHealth: health,
    roadmap: roadmapItems,
    sessionReminderTemplates: reminderTemplates,
    clientReminderSettings: clientSettings,
    upcomingReminders: reminders,
    welcomeSequences: welcomeSeqs,
    absenceAutomations: absenceAutos,
    messageTemplates,
    scheduledMessages: scheduledMsgs,
    inactivityAutomations: inactivityAutos,
    importantDateAutomations: importantDateAutos,
    paymentReminderAutomations: paymentReminderAutos,
    messageStatisticsDashboard: messageStats,
    clientSegments: clientSegs,
    bulkMessages: bulkMsgs,
    newsletters: newslettersData,
    newsletterTemplates: newsletterTemps,
    afterHoursAutoReplies: afterHoursReplies,
    promotionalCampaigns: promotionalCamps,
    reservationsIntegration,
    centralAutomationsPanel,
    messageAlertsDashboard,
    preferredSendingSchedulesDashboard,
    multiStepSequences: multiStepSeqs,
    exportReports: exportReps,
  };
}









